<div class="container">
    <div class="text_block" >
        <h3 class="title">Контакты</h3>
        <div class="text_caption">
            <p><b>Адрес: </b><?= $this->info_city[0]['addres']; ?></p>
            <p><b>Телефон/факс: </b><?= $this->info_city[0]['phone']; ?></p>
            <p><b>E-mail: </b><?= $this->info_city[0]['email']; ?></p>
			<? if ($this->info_city[0]['id'] == 2) : ?>
				<p><b>ICQ: </b>665140899</p>
			<? endif; ?>
            <p>
                <strong>ОГРН:</strong><?= $this->info_city[0]['ogrn']; ?><br />
                <strong>ИНН:</strong><?= $this->info_city[0]['inn']; ?><br />
                <strong>КПП:</strong><?= $this->info_city[0]['kpp']; ?><br />
            </p>
            <p>
            <h3>Схема проезда:</h3>
            <script type="text/javascript" charset="utf-8" src="<?= $this->info_city[0]['yandex']; ?>"></script>
            </p>
        </div>

    </div>
</div>