
<div class="container">
    <div class="text_block" >
        <h3 class="title">Персональный трекер</h3>
        <div class="text_caption">
            <div class="row">
                <div class="span5">
                    <img src="/img/equipment/helpbutton/3.png" class="img_view">
                </div>
                <div class="span6">
                    <p class="buttons">
                        <a href="#" class="button_b">Купить Персональный трекер</a>
                        <a href="#" class="button_s">Цена на Персональный трекер</a>
                    </p>
                    <h4>А так же для оформления заказа звоните на бесплатную горячую линию: 8(800) 500-17-14</h4>

                </div>
            </div>
            <p>Удобный и компактный мини трекер - это идеальное решение для тех, за кого вы особенно волнуетесь:</p>
            <ul class="marker">
                <li>Для пожилых людей, чтобы всегда иметь кнопку SOS под рукой</li>
                <li>Просто необходим для тех, кто недавно перенес операцию или приступ</li>
                <li>Незаменим для родителей, которые отправляют ребенка одного в школу.</li>
            </ul>
        </div>

    </div>
</div>