<div class="container">
    <div class="text_block" >
        <h3 class="title">Кнопка доверия</h3>
        <div class="text_caption">
            <p>
                По статистике 30% пожилых людей старше 65 лет падают один раз в год или чаще. 
                После падения более половины из них не могут самостоятельно подняться и позвать на помощь. 
            </p>
            <p>
                Более 7% падений заканчиваются переломами, около 10% – серьезными травмами головы, 
                внутренних органов, а иногда летальным исходом. 
            </p>
            <p>Кнопка Доверия может помочь вашему близкому человеку уже сегодня! </p>

            <h3>Описание</h3>
            <img src="/img/operator.png" class="all_img">
            <p>
                Все сигналы от устройства SOS моментально поступают в круглосуточный Диспетчерский Центр, 
                где на линии круглосуточно дежурит врач. При поступлении сигнала, оператор определяет причину вызова и 
                направляет необходимую помощь: скорую, полицию, МЧС и другие службы, а также оповещает родственников, 
                соседей и родственников, указанных при активации услуги.
            </p>

            <p>
                В экстренной ситуации пожилому человеку или ребенку бывает трудно самостоятельно дозвониться до 
                экстренной службы или занятых на работе родственников . В особенности тяжело это сделать 
                пожилым людям и инвалидам . Пропущенный из-за ожидания на линии или сброшенный вызов может 
                закончится очень печально …
            </p>

            <p>
                В Диспетчерском Центре Кнопки Доверия ни один вызов не будет потерян! 
                Даже если пользователь сбросил звонок - информация о пропущенном вызове сразу же поступает на пульт, 
                диспетчер будет дозваниваться до человека пока не удостоверится, что с Подопечным все в порядке.
            </p><br /><br />
            <img src="/img/callcenter.jpg" class="all_img">
            <p>
                В момент звонка врач-оператор уже видит на экране, от кого поступил сигнал, где человек находится, 
                а также всю необходимую информацию о ключевых заболеваниях и аллергических реакциях на препараты 
                для более оперативного и эффективного реагирования.
            </p>
            <p>
                Большинство устройств поддерживают функцию геолокации и в режиме реального времени показывают 
                местоположение человека.
            </p>

            <p>В момент звонка диспетчер видит на карте, где находится человек, а также всю историю его последних перемещений.</p>


            <div class="trackers">
                <div style="position: relative;">
                    <a href="<?php
                    echo $this->url(
                            array(
                        'controller' => 'index',
                        'action' => 'hbutton1'
                            ), 'default', true)
                            ?>"><img src="/img/equipment/helpbutton/1.png" class="img_n" style="height: 170px;"></a>
                </div>
                <div class="tracker_text">
                    <p><a href="<?php
                        echo $this->url(
                                array(
                            'controller' => 'index',
                            'action' => 'hbutton1'
                                ), 'default', true)
                        ?>">Домашняя станция + SOS кулон</a></p>
                    <p class="buttons">
                        
                    </p>
                </div>
            </div>
            
            <div class="trackers">
                <div style="position: relative;">
                    <a href="<?php
                    echo $this->url(
                            array(
                        'controller' => 'index',
                        'action' => 'hbutton2'
                            ), 'default', true)
                    ?>"><img src="/img/equipment/helpbutton/2.jpg" class="img_n" style="height: 170px;"></a>
                </div>
                <div class="tracker_text">
                    <p><a href="<?php
                        echo $this->url(
                                array(
                            'controller' => 'index',
                            'action' => 'hbutton2'
                                ), 'default', true)
                        ?>">Мобильный телефон с кнопкой SOS</a></p>
                    <p class="buttons">
                        
                    </p>
                </div>
            </div>
            
            <div class="trackers">
                <div style="position: relative;">
                    <a href="<?php
                    echo $this->url(
                            array(
                        'controller' => 'index',
                        'action' => 'hbutton3'
                            ), 'default', true)
                    ?>"><img src="/img/equipment/helpbutton/3.png" class="img_n" style="height: 170px;"></a>
                </div>
                <div class="tracker_text">
                    <p><a href="<?php
                        echo $this->url(
                                array(
                            'controller' => 'index',
                            'action' => 'hbutton3'
                                ), 'default', true)
                        ?>">Персональный <br />трекер</a></p>
                    <p class="buttons">
                        
                    </p>
                </div>
            </div>
            
            <div class="trackers">
                <div style="position: relative;">
                    <a href="<?php
                    echo $this->url(
                            array(
                        'controller' => 'index',
                        'action' => 'hbutton4'
                            ), 'default', true)
                    ?>"><img src="/img/equipment/helpbutton/4.png" class="img_n" style="height: 170px; margin: 0 30px;"></a>
                </div>
                <div class="tracker_text">
                    <p><a href="<?php
                        echo $this->url(
                                array(
                            'controller' => 'index',
                            'action' => 'hbutton4'
                                ), 'default', true)
                        ?>">Проверочный звонок "Все ХОРОШО!"</a></p>
                    <p class="buttons">
                        
                    </p>
                </div>
            </div>
            
            <div class="trackers">
                <div style="position: relative;">
                    <a href="<?php
                    echo $this->url(
                            array(
                        'controller' => 'index',
                        'action' => 'hbutton5'
                            ), 'default', true)
                    ?>"><img src="/img/equipment/helpbutton/5.jpg" class="img_n" style="height: 170px; margin: 0 30px;"></a>
                </div>
                <div class="tracker_text">
                    <p><a href="<?php
                        echo $this->url(
                                array(
                            'controller' => 'index',
                            'action' => 'hbutton5'
                                ), 'default', true)
                        ?>">Программа финансовой помощи.</a></p>
                    <p class="buttons">
                        
                    </p>
                </div>
            </div>
            
        </div>

    </div>
</div>