<div class="carousel slide" id="myCarousel">
    <ol class="carousel-indicators">
        <li class="active" data-target="#myCarousel" data-slide-to="0"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>

    <div class="carousel-inner">
        <div class="item active">
            <img src="./img/ban1.jpg">
            <div class="carousel-caption">
                <h4>title</h4>
                <p>text text text text </p>
            </div>
        </div>
        <div class="item">
            <img src="./img/ban2.png">
            <div class="carousel-caption">
                <h4>title</h4>
                <p>text text text text </p>
            </div>
        </div>
        <div class="item">
            <img src="./img/ban3.png">
            <div class="carousel-caption">
                <h4>title</h4>
                <p>text text text text </p>
            </div>
        </div>
    </div>
    <a class="carousel-control left" data-slide="prev" href="#myCarousel">&lsaquo;</a>
    <a class="carousel-control right" data-slide="next" href="#myCarousel">&rsaquo;</a>
</div>

<div class="container">
    <div class="news_block" >
        <h3>Новости</h3>
        <div class=" news_one">
            <div style="position: relative;">
                <img src="./img/news/tamojgnya-planiruet-ispolzovat-glonass.jpg">
                <div class="photo_title">
                    <p>05.02.2014</p>
                    <h6>Таможня планирует использовать ГЛОНАСС для отслеживания товаров Таможня планирует использовать ГЛОНАСС для отслеживания товаров</h6>
                </div>
            </div>
            <div class="news_text">
                Сергей Коноваленко, начальник управления таможенного сотрудничества федеральной таможенной службы России, 
                огласил намерения ФТС использовать навигационную спутниковую систему ГЛОНАСС с целью получения данных о 
                фактическом товарообороте между Россией и странами Европы. 

            </div>
        </div>
        <div class=" news_one">
            <div style="position: relative;">
                <img src="./img/news/sistemu-glonass-osvaivayut-artileristy.jpg">
                <div class="photo_title">
                    <p>05.02.2014</p>
                    <h6>Систему ГЛОНАСС осваивают российские артиллеристы Систему ГЛОНАСС осваивают российские артиллеристы</h6>
                    
                </div>
            </div>
            <div class="news_text">
                В соответствии с официальными сообщениями от пресс-службы Южного военного округа, 
                местные артиллеристы пользуются системой ГЛОНАСС для того, чтобы определять координаты мишеней 
                на территории полигона под названием “Прудбой” (Волгоградская область).
            </div>
        </div>
        <div class=" news_one">
            <div style="position: relative;">
                <img src="./img/news/glonass-pomog-vracham-posle-terakta.jpg">
                <div class="photo_title">
                    <p>05.02.2014</p>
                    <h6>ГЛОНАСС помог врачам после волгоградского теракта</h6>
                </div>
            </div>
            <div class="news_text">
                29 декабря, после теракта в Волгограде, ГЛОНАСС пришла на помощь водителям машин «Скорой помощи». 
                Она передавала данные о том, где сейчас находится врачебный транспорт, таким образом, 
                помогая быстро и эффективно определять раненных в нужные больницы.
            </div>
        </div>
    </div>
</div>



