

<div class="carousel slide" id="myCarousel">
    <ol class="carousel-indicators">
        <li class="active" data-target="#myCarousel" data-slide-to="0"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>

    <div class="carousel-inner">
        <div class="item active">
            <img src="./img/glonass-fon.jpg">
            <div class="carousel_text">
                <h4>ГЛОНАСС мониторинг</h4>
                <p>Оборудование, соответствующее требованиям федерального закона РФ от 14 февраля 2009 г. N 22-ФЗ "О навигационной деятельности". 
                    Выдача необходимых документов для прохождения лицензирования и технического осмотра.</p>
                <div class="button_s" style="float: right;" onclick="location.href = '<?php
                echo $this->url(
                        array(
                    'controller' => 'uslugi',
                    'action' => 'glonass'
                        ), 'default', true)
                ?>';">Подробнее...</div>
            </div>
        </div>
        <div class="item">
            <img src="./img/logo-kontrol-topliva.jpg">
            <div class="carousel_text">
                <h4>Контроль топлива</h4>
                <p>Датчики уровня топлива LLS
                    производства Omnicomm. 
                    Пожизненная гарантия! Установка 
                    датчика уровня топлива позволит 
                    сделать систему контроля ГСМ 
                    максимально прозрачной.</p>
                <div class="button_s" style="float: right;" onclick="location.href = '<?php
                echo $this->url(
                        array(
                    'controller' => 'uslugi',
                    'action' => 'kontroltopliva'
                        ), 'default', true)
                ?>';">Подробнее...</div>
            </div>
        </div>
        <div class="item">
            <img src="./img/system-paralel-fon.jpg">
            <div class="carousel_text">
                <h4>Системы параллельного вождения</h4>
                <p>Ресурсосберегающие технологии для сельского хозяйства от культовой компании Trimble. Навигация для посева и опрыскивания.</p>
                <div class="button_s" style="float: right;" onclick="location.href = '<?php
                echo $this->url(
                        array(
                    'controller' => 'industry',
                    'action' => 'parallels'
                        ), 'default', true)
                ?>';">Подробнее...</div> 
            </div>
        </div>
    </div>
    <a class="carousel-control left" data-slide="prev" href="#myCarousel">&lsaquo;</a>
    <a class="carousel-control right" data-slide="next" href="#myCarousel">&rsaquo;</a>
</div>

<div class="container">
    <div class="news_block" style="width: 940px;">
        <h3 class="title"><a href="<?php
            echo $this->url(
                    array(
                'controller' => 'index',
                'action' => 'news'
                    ), 'default', true)
            ?>">Новости</a></h3>
            <? $bb = new Application_Model_Index(); ?>
            <?
            $i = 0;
            foreach ($this->news as $news) :
                ?>
                <? if ($i < 4) : ?>

                <div class="news_one" style="float: left; margin-right: 3px;" onclick="location.href = '<?php
                echo $this->url(
                        array(
                    'controller' => 'index',
                    'action' => 'newsinfo'
                        ), 'default', true)
                ?>/id/<?= $news['id']; ?>'">
                    <div style="position: relative;">
                        <? if ($news['img'] != '') : ?>
                            <img src="./img/news/<?= $news['img']; ?>" class="img_n">
                        <? else : ?>
                            <img src="/img/logo.png" class="img_n">
                        <? endif; ?>
                        <div class="photo_title">
                            <p><?= date('d.m.Y', strtotime($news['datetime'])); ?></p>
                            <h6><?= $news['title']; ?></h6>
                        </div>
                    </div>
                    <div class="news_text">
                        <?
                        $text_news = '';
                        if (mb_strlen($news['text']) > 300) {
                            $text_news = mb_substr($news['text'], 0, 300, 'utf-8') . '...';
                        } else {
                            $text_news = $news['text'];
                        }
                        ?>
                        <?= nl2br($bb->bb_tags($text_news)); ?>
                    </div>
                </div>

            <? endif; ?>
            <?
            $i++;
        endforeach;
        ?>
    </div>

    <div class="block_map">
        <div class="moscow">Москва</div>
        <div class="moscow_info">
            <a href="/index/about" class="set_city2"><strong>Центральный офис</strong></a>
            <address><em>г. Москва, Шоссе Энтузиастов, 56 стр.44</em></address>
        </div>
        <div class="stav">Ставрополь</div>
        <div class="stav_info">
            <a href="/index/about" class="set_city1"><strong>Филиал в г.Ставрополь</strong></a>
            <address><em>г. Ставрополь, ул. Гражданская, д. 8</em></address>
        </div>
    </div>
</div>

<script>

    $(function() {
        $('.carousel').carousel({
            interval: 3000
        });
    });

    $('.moscow').mouseenter(function() {
        $('.moscow').animate({fontSize: "3em"}, 100, function() {
            $('.moscow_info').css('display', 'block');
        });
    });
    $('.moscow_info').mouseleave(function() {
        $('.moscow').animate({fontSize: "1em"}, 100);
        $('.moscow_info').css('display', 'none');
    });

    $('.stav').mouseenter(function() {
        $('.stav').animate({fontSize: "3em"}, 100, function() {
            $('.stav_info').css('display', 'block');
        });
    });
    $('.stav_info').mouseleave(function() {
        $('.stav').animate({fontSize: "1em"}, 100);
        $('.stav_info').css('display', 'none');
    });

    $('.set_city2').click(function() {
        id = 2;
        expires = new Date(); // получаем текущую дату
        expires.setTime(expires.getTime() + (1000 * 86400 * 365)); // вычисляем срок хранения cookie
        set_cookie('id_city', id, expires); // устанавливаем cookie с помощью функции set_cookie
    });

    $('.set_city1').click(function() {
        id = 1;
        expires = new Date(); // получаем текущую дату
        expires.setTime(expires.getTime() + (1000 * 86400 * 365)); // вычисляем срок хранения cookie
        set_cookie('id_city', id, expires); // устанавливаем cookie с помощью функции set_cookie
    })
</script>

