

<div class="carousel slide" id="myCarousel">
    <ol class="carousel-indicators">
        <li class="active" data-target="#myCarousel" data-slide-to="0"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>

    <div class="carousel-inner">
        <div class="item active">
            <img src="./img/glonass-fon.jpg">
            <div class="carousel_text">
                <h4>ГЛОНАСС мониторинг</h4>
                <p>Оборудование, соответствующее требованиям федерального закона РФ от 14 февраля 2009 г. N 22-ФЗ "О навигационной деятельности". 
                    Выдача необходимых документов для прохождения лицензирования и технического осмотра.</p>
                <div class="button_s" style="float: right;" onclick="location.href = '<?php
                echo $this->url(
                        array(
                    'controller' => 'uslugi',
                    'action' => 'glonass'
                        ), 'default', true)
                ?>';">Подробнее...</div>
            </div>
        </div>
        <div class="item">
            <img src="./img/logo-kontrol-topliva.jpg">
            <div class="carousel_text">
                <h4>Контроль топлива</h4>
                <p>Датчики уровня топлива LLS
                    производства Omnicomm. 
                    Пожизненная гарантия! Установка 
                    датчика уровня топлива позволит 
                    сделать систему контроля ГСМ 
                    максимально прозрачной.</p>
                <div class="button_s" style="float: right;" onclick="location.href = '<?php
                echo $this->url(
                        array(
                    'controller' => 'uslugi',
                    'action' => 'kontroltopliva'
                        ), 'default', true)
                ?>';">Подробнее...</div>
            </div>
        </div>
        <div class="item">
            <img src="./img/system-paralel-fon.jpg">
            <div class="carousel_text">
                <h4>Системы параллельного вождения</h4>
                <p>Ресурсосберегающие технологии для сельского хозяйства от культовой компании Trimble. Навигация для посева и опрыскивания.</p>
                <div class="button_s" style="float: right;" onclick="location.href = '<?php
                echo $this->url(
                        array(
                    'controller' => 'industry',
                    'action' => 'parallels'
                        ), 'default', true)
                ?>';">Подробнее...</div> 
            </div>
        </div>
    </div>
    <a class="carousel-control left" data-slide="prev" href="#myCarousel">&lsaquo;</a>
    <a class="carousel-control right" data-slide="next" href="#myCarousel">&rsaquo;</a>
</div>

<div class="container">
    <div class="news_block" >
        <h3 class="title"><a href="<?php
            echo $this->url(
                    array(
                'controller' => 'index',
                'action' => 'news'
                    ), 'default', true)
            ?>">Новости</a></h3>
            <? $i = 0;
            foreach ($this->news as $news) :
                ?>
    <? if ($i < 4) : ?>
                <a href="#">
                    <div class="news_one">
                        <div style="position: relative;">
                            <img src="<?= $news['img']; ?>" class="img_n">
                            <div class="photo_title">
                                <p><?= date('d.m.Y', strtotime($news['datetime'])); ?></p>
                                <h6><?= $news['title']; ?></h6>
                            </div>
                        </div>
                        <div class="news_text">
                            <?
                            $text_news = '';
                            if (mb_strlen($news['text']) > 300) {
                                $text_news = mb_substr($news['text'], 0, 300, 'utf-8') . '...';
                            } else {
                                $text_news = $news['text'];
                            }
                            ?>
        <?= $text_news; ?>
                        </div>
                    </div>
                </a>
            <? endif; ?>
            <? $i++;
        endforeach;
        ?>
    </div>

    <div class="block_map">
        <div class="moscow">Москва</div>
        <div class="moscow_info">
            <address><em>г. Москва, Шоссе Энтузиастов, 56 стр.44</em></address>
        </div>
        <div class="stav">Ставрополь</div>
        <div class="stav_info">
            <address><em>г. Ставрополь, ул. Гражданская, д. 8</em></address>
        </div>
    </div>
</div>

<script>

    $(function() {
        $('.carousel').carousel({
            interval: 3000
        });
    });

    $('.moscow').hover(function() {
        $('.moscow_info').toggle('slow');
    });

    $('.stav').hover(function() {
        $('.stav_info').toggle('slow');
    });
</script>

