<div class="container">
    <div class="text_block" >
        <h3 class="title">Оплата</h3>
        <div class="text_caption">
            <p>
                Уважаемые клиенты и гости сайта, Вы можете оплатить услугу по предоставлению доступа к мониторингу транспорта через Интернет.
                Внимание! При оплате, не забудьте указать номер договора и контактное лицо плательщика.
            </p>
            <div style="display: block; width: 450px; margin: 0 auto;">
                <iframe frameborder="0" allowtransparency="true" scrolling="no" src="https://money.yandex.ru/embed/shop.xml?account=41001963564205&quickpay=shop&payment-type-choice=on&writer=buyer&targets-hint=%D0%9D%D0%BE%D0%BC%D0%B5%D1%80+%D0%B4%D0%BE%D0%B3%D0%BE%D0%B2%D0%BE%D1%80%D0%B0+%D0%B8+%D0%BA%D0%BE%D0%BD%D1%82%D0%B0%D0%BA%D1%82%D0%BD%D0%BE%D0%B5+%D0%BB%D0%B8%D1%86%D0%BE+%D0%BF%D0%BB%D0%B0%D1%82%D0%B5%D0%BB%D1%8C%D1%89%D0%B8%D0%BA%D0%B0&default-sum=1&button-text=01&comment=on&hint=&successURL=" width="450" height="264"></iframe>
            </div>
        </div>

    </div>
</div>