<div class="container">
    <div class="text_block" >
        <h3 class="title">Служба заботы о клиенте</h3>
        <div class="text_caption">
            <img src="/img/support.jpg" class="img">
            <p>В нашем бизнесе есть только один гуру, к чьим словам мы прислушиваемся всегда. Этот гуру – Вы, наши клиенты.</p>
            <p>Не удивляйтесь, но именно Вы стоите во главе всех преобразований в компании, Вы позволяете нам расти и совершенствоваться. Без Вас эволюция в профессиональном плане невозможна.</p>
            <p>Вы можете сделать нас лучше. Мы умеем слушать. Мы готовы повышать профессионализм и доказывать свою полезность для Вас.</p>
            <p>Мы создали службу заботы о клиенте, чтобы быть ближе к Вам. Мы открыты для диалога.</p>
            <p>На этой странице Вы можете оставить отзыв или пожелания. Ни один из них не останется без нашего внимания. Ни один из них не будет бесполезным для нас. Спасибо.</p>
            <p><strong>Телефон:</strong> 8 (800) 500-17-14</p>
            <p><strong>E-mail:</strong> info@art-track.ru</p>

            <p>Конфиденциальность гарантируем</p>
            <div class="form_support">
                <form method="post">
                    <div class="control-group">
                        <div class="controls">
                            <label><input type="text" name="name" placeholder="Ваше имя" required></label>
                        </div>
                        <div class="controls">
                            <label><input type="text" name="phone" placeholder="Ваш телефон" required></label>
                        </div>
                        <div class="controls">
                            <label><input type="email" name="email" placeholder="Ваш e-mail" required></label>
                        </div>
                        <div class="controls">
                            <label><textarea placeholder="Ваше обращение" name="comment" required></textarea></label>
                        </div>
                        <div class="controls">
                            <label style="margin-left: 40px;" class="buttons"><a href="#" class="button_s send_message">Отправить отзыв</a></label>
                        </div>
                    </div>
                </form>
            </div>
        </div>

    </div>
</div>

<script>
    var params = {};
    $('.send_message').click(function() {
        $form = $('form');
        if ($form.find('input[name=name]').val() == '') {
            alert('Введите имя');
            return false;
        } else {
            params.name = $form.find('input[name=name]').val();
        }
        if ($form.find('input[name=phone]').val() == '') {
            alert('Введите телефон');
            return false;
        } else {
            params.phone = $form.find('input[name=phone]').val();
        }
        if ($form.find('input[name=email]').val() == '') {
            alert('Введите email');
            return false;
        } else {
            params.email = $form.find('input[name=email]').val();
        }
        if ($form.find('textarea[name=comment]').val() == '') {
            alert('Введите сообщение');
            return false;
        } else {
            params.comment = $form.find('textarea[name=comment]').val();
        }
        params.support = 1;
        $.post('/index/support/', params, function(data) {
            $form.find('input[name]').val('');
            $form.find('textarea[name]').val('');
            alert('Спасибо, Ваше мнение важно для нас');
        });

        return false;
    });

</script>