<div class="container">
    <div class="text_block" >
        <h3 class="title">Служба заботы о клиенте</h3>
        <div class="text_caption">
            <p>В нашем бизнесе есть только один гуру, к чьим словам мы прислушиваемся всегда. Этот гуру – Вы, наши клиенты.</p>
            <p>Не удивляйтесь, но именно Вы стоите во главе всех преобразований в компании, Вы позволяете нам расти и совершенствоваться. Без Вас эволюция в профессиональном плане невозможна.</p>
            <p>Вы можете сделать нас лучше. Мы умеем слушать. Мы готовы повышать профессионализм и доказывать свою полезность для Вас.</p>
            <p>Мы создали службу заботы о клиенте, чтобы быть ближе к Вам. Мы открыты для диалога.</p>
            <p>На этой странице Вы можете оставить отзыв или пожелания. Ни один из них не останется без нашего внимания. Ни один из них не будет бесполезным для нас. Спасибо.</p>
            <p>Телефон: 8 (800) 500-17-14</p>
            <p>E-mail: info@art-track.ru</p>

            <p>Конфиденциальность гарантируем</p>
            <div class="form_support">
                <form method="post">
                    <div class="control-group">
                        <div class="controls">
                            <label><input type="text" placeholder="Ваше имя" required></label>
                        </div>
                        <div class="controls">
                            <label><input type="text" placeholder="Ваш телефон" required></label>
                        </div>
                        <div class="controls">
                            <label><input type="email" placeholder="Ваш e-mail" required></label>
                        </div>
                        <div class="controls">
                            <label><textarea placeholder="Ваше обращение" required></textarea></label>
                        </div>
                        <div class="controls">
                            <label style="margin-left: 40px;" class="buttons"><a href="#" class="button_s">Отправить отзыв</a></label>
                        </div>
                    </div>
                </form>
            </div>
        </div>

    </div>
</div>