<form method="POST">
    <!--[if IE]><label>Ваше имя</label><![endif]-->
    <input type="text" name="name" placeholder="Ваше имя" required />
    <!--[if IE]><label>Ваш город</label><![endif]-->
    <input type="text" name="city" placeholder="Ваш город" required />
    <!--[if IE]><label>Ваш телефон</label><![endif]-->
    <input type="tel" name="phone" placeholder="Ваш телефон" required />
    <!--[if IE]><label>Ваш звонить</label><![endif]-->
    <input type="text" name="then" placeholder="Когда звонить" required />
    <a href="#" class="button_s set_order" style="margin: 0 70px;">Заказать</a>
</form>

<script>
    var params = {};
    $('.set_order').click(function() {
        $form = $('form');
        if ($form.find('input[name=name]').val() == '') {
            alert('Введите имя');
            return false;
        } else {
            params.name = $form.find('input[name=name]').val();
        }
        if ($form.find('input[name=city]').val() == '') {
            alert('Введите город');
            return false;
        } else {
            params.city = $form.find('input[name=city]').val();
        }
        if ($form.find('input[name=phone]').val() == '') {
            alert('Введите телефон');
            return false;
        } else {
            params.phone = $form.find('input[name=phone]').val();
        }
        if ($form.find('input[name=then]').val() == '') {
            alert('Введите время когда Вам позвонить');
            return false;
        } else {
            params.then = $form.find('input[name=then]').val();
        }
        params.addtell = 1;
        $.post('/index/tellorder/', params, function(data) {
            $('.form_call').slideToggle();
            $form.find('input[name]').val('');
            alert('Спасибо, ваша заявка принята');
        });

        return false;
    });

</script>
