<div class="container">
    <div class="text_block" >
        <h3 class="title">Ретранслятор</h3>
        <div class="text_caption">
            <p>Вам требуется заключение о передаче мониторинговой информации в РНИЦ?</p>
            <p>Вам нужно продлить лицензию на перевозку пассажиров или опасных грузов?</p>

            <p>Сервис "Ретранслятор" позволит Вам выполнить условия законодательства минимальными усилиями и в короткие сроки.</p>

            <p>Согласно требованиям Приказа Минтранса РФ от 26.01.2012 №20 все транспортные средства категории М2 и M3, используемые для коммерческих перевозок пассажиров, а также N, используемые для перевозки опасных грузов, подлежат оснащению аппаратурой спутниковой навигации ГЛОНАСС или ГЛОНАСС/GPS, а данные мониторинга подлежат обязательной передаче в АЦКН Ространснадзора (либо уполномоченный орган субъекта РФ).</p>

            <h4>Сервис «Ретранслятор» включает:</h4>
            <ul class="marker">
                <li>Программное обеспечение (службу) Ретранслятор, которая передаёт информацию из системы Art-Track в стороннюю мониторинговую систему (РНИЦ)</li>
                <li>Настройку службы на передачу мониторинговой информации с конкретного автомобиля в конкретный контролирующий орган (РНИЦ)</li>
                <li>Получение подтверждения из РНИЦ об успешной передаче мониторинговой информации</li>
                <li>Регулярная ретрансляция данных в АЦКН Ространснадзор</li>
                <li>Получение на ваше имя сертификата о подключении к РНИЦ (опционально)</li>
                <li>Получение на ваше имя лицензии на перевозку пассажиров и опасных грузов (опционально)</li>
            </ul>
            <h4>Состав передаваемой информации:</h4>
            <ul class="marker">
                <li>идентификационный номер абонентского телематического терминала;</li>
                <li>географическая широта местоположения транспортного средства;</li>
                <li>географическая долгота местоположения транспортного средства;</li>
                <li>скорость движения транспортного средства;</li>
                <li>путевой угол транспортного средства;</li>
                <li>время и дата фиксации местоположения транспортного средства;</li>
                <li>признак передачи сигнала бедствия (при наличии тревожной кнопки).</li>
            </ul>

            <h4>Заполните форму для подключения</h4>
            <form method="post">
                <div class="control-group">
                    <div class="controls">
                        <label><input type="text" name="fio" placeholder="ФИО" required></label>
                    </div>
                    <div class="controls">
                        <label><input type="text" name="company" placeholder="Компания" required></label>
                    </div>
                    <div class="controls">
                        <select name="otrasl">
                            <option>Отрасль</option>
                            <option>Транспорт</option>
                            <option>Логистика</option>
                            <option>Горнодобывающая промышленность</option>
                            <option>Строительство</option>
                            <option>Сельское хозяйство</option>
                            <option>Ритейл</option>
                            <option>Дистрибуция</option>
                            <option>ТЭКЖКХ</option>
                            <option>Другое</option>
                        </select>
                    </div>
                    <div class="controls">
                        <select name="count_ts">
                            <option>Количество транспортных средств</option>
                            <option>меньше 10</option>
                            <option>10-50</option>
                            <option>50-100</option>
                            <option>100-500</option>
                            <option>500-больше</option>
                        </select>
                    </div>
                    <div class="controls">
                        <label><input type="text" name="city" placeholder="Город" required></label>
                    </div>
                    <div class="controls">
                        <label><input type="text" name="phone" placeholder="Телефон" required></label>
                    </div>
                    <div class="controls">
                        <label><input type="email" name="email" placeholder="Ваш e-mail" required></label>
                    </div>
                    <div class="controls">
                        <label style="margin-left: 50px;"><a href="#" class="button_s send_retr">Отправить</a></label>
                    </div>
                </div>
            </form>
        </div>

    </div>
</div>

<script>
    var params = {};
    $('.set_order').click(function() {
        $form = $('form');
        if ($form.find('input[name=fio]').val() == '') {
            alert('Введите имя');
            return false;
        } else {
            params.fio = $form.find('input[name=fio]').val();
        }
        if ($form.find('input[name=company]').val() == '') {
            alert('Введите компанию');
            return false;
        } else {
            params.company = $form.find('input[name=company]').val();
        }
        if ($form.find('select[name=otrasl]').val() == 'Отрасль') {
            alert('Выберите отрасль');
            return false;
        } else {
            params.otrasl = $form.find('input[name=otrasl]').val();
        }
        if ($form.find('select[name=count_ts]').val() == 'Количество транспортных средств') {
            alert('Выберите количество ТС');
            return false;
        } else {
            params.count_ts = $form.find('input[name=count_ts]').val();
        }
        if ($form.find('input[name=city]').val() == '') {
            alert('Введите город');
            return false;
        } else {
            params.city = $form.find('input[name=city]').val();
        }
        if ($form.find('input[name=phone]').val() == '') {
            alert('Введите телефон');
            return false;
        } else {
            params.phone = $form.find('input[name=phone]').val();
        }
        if ($form.find('input[name=email]').val() == '') {
            alert('Введите email');
            return false;
        } else {
            params.email = $form.find('input[name=email]').val();
        }
        params.addretrans = 1;
        $.post('/uslugi/retranslyator/', params, function(data) {
            $form.find('input[name]').val('');
            alert('Спасибо, ваша заявка принята');
        });

        return false;
    });

</script>
