<div class="container">
    <div class="text_block" >
        <h3 class="title">Услуги по мониторингу автотранспорта</h3>
        <div class="text_caption">
            <div class="uslugi_info" onclick="location.href = '<?php
            echo $this->url(
                    array(
                'controller' => 'uslugi',
                'action' => 'kontroltopliva'
                    ), 'default', true)
            ?>';">
                <img src="/img/uslugi/kontrol-topliva.jpg" class="img_uslugi_info">
                <h4>Контроль расхода топлива</h4>
                <p>
                    Сливы топлива? Повышенный расход? «Левые» чеки с заправок? Обналичивают топливные карты? 
                    Хватит терпеть воровство! Контроль топлива на базе системы мониторинга ГЛОНАСС/GPS – вот, 
                    что Вам нужно.
                </p>
            </div>

            <div class="uslugi_info" onclick="location.href = '<?php
            echo $this->url(
                    array(
                'controller' => 'uslugi',
                'action' => 'glonass'
                    ), 'default', true)
            ?>';">
                <img src="/img/uslugi/uslugi-glonass-monit.png" class="img_uslugi_info">
                <h4>ГЛОНАСС мониторинг транспорта</h4>
                <p>
                    Установка системы ГЛОНАСС мониторинга транспорта позволит Вам не только успешно 
                    пройти технический осмотр, получить лицензию на перевозку пассажиров, побеждать 
                    в государственном тендере, но и главное - сократить расходы на содержание транспорта.
                </p>
            </div>

            <div class="uslugi_info" onclick="location.href = '<?php
            echo $this->url(
                    array(
                'controller' => 'uslugi',
                'action' => 'gps'
                    ), 'default', true)
            ?>';">
                <img src="/img/uslugi/uslugi-gps-monit.jpg" class="img_uslugi_info">
                <h4>GPS мониторинг транспорта</h4>
                <p>
                    Кто владеет информацией — тот владеет миром. Знаменитое выражение и сейчас не 
                    потеряло своей актуальности. GPS мониторинг транспорта дает такую информацию! 
                    Вы знаете где, когда и во сколько была Ваша машина, с какой скоростью двигалась, 
                    сколько топлива было потрачено. И все это в режиме реального времени.
                </p>
            </div>

            <div class="uslugi_info" onclick="location.href = '<?php
            echo $this->url(
                    array(
                'controller' => 'industry',
                'action' => 'parallels'
                    ), 'default', true)
            ?>';">
                <img src="/img/uslugi/uslugi-kursoukozatel.jpg" class="img_uslugi_info">
                <h4>Установка систем параллельного вождения</h4>
                <p>
                    Повышайте эффективность сельскохозяйственных работ. Системы параллельного 
                    вождения позволят работать без перекрытий и огрехов 24 часа в сутки, контролировать 
                    качество выполненных работ и делать любой сельскохозяйственный процесс приятнее и продуктивнее.
                </p>
            </div>

            <div class="uslugi_info" onclick="location.href = '<?php
            echo $this->url(
                    array(
                'controller' => 'industry',
                'action' => 'gruzoperevozki'
                    ), 'default', true)
            ?>';">
                <img src="/img/uslugi/uslugi-gotovie-resheniya.jpg" class="img_uslugi_info">
                <h4>Готовые решения по контролю транспорта</h4>
                <p>
                    ГЛОНАСС/GPS мониторинг транспорта — инструмент, без которого не могут обойтись тысячи предприятий.
                    Эффективность системы порой поражает! Есть предприятия, где после внедрения систем 
                    спутникового мониторинга и расхода топлива снижение расходов на содержание автопарка 
                    составило 50%.
                </p>
            </div>
        </div>

    </div>
</div>