<div class="container">
    <div class="text_block" >
        <h3 class="title">Часто задаваемые вопросы</h3>
        <div class="text_caption">
            <div class="service_style">
                <span id="faq1">Какая гарантия на оборудование?</span>
                <div class="faq1" id="kat" style="display: none;">
                    <p>
                        Компания Арттрэк предлагает пожизненную гарантию на спутниковые GPS/ГЛОНАСС терминалы и 
                        датчики уровня топлива Омником.
                    </p>
                </div>

                <span id="faq2">Из чего складывается ежемесячная абонентская плата?</span>
                <div class="faq2" id="kat" style="display: none;">
                    <ul class="marker">
                        <li>Оплата трафика сим-карт;</li>
                        <li>Диспетчерское ПО;</li>
                        <li>Выезд специалиста к клиенту в случае неисправности;</li>
                        <li>Обучение по работе с ПО.</li>
                    </ul>
                </div>

                <span id="faq3">Насколько быстро устраняются неисправности системы?</span>
                <div class="faq3" id="kat" style="display: none;">
                    <p>
                        Большинство проблем с ПО возможно решить удаленно и на это уходит минимум времени. 
                        Для исправления неисправностей оборудования у нас существует золотое правило «48 часов» 
                        на реагирование.
                    </p>
                    <p>
                        В случае, если неисправность системы не была исправлена в течение 48 часов, 
                        то последующие 2 месяца данное оборудование обслуживается бесплатно.
                    </p>
                </div>

                <span id="faq4">Из чего складывается стоимость системы?</span>
                <div class="faq4" id="kat" style="display: none;">
                    <ul class="marker">
                        <li>Стоимость оборудования;</li>
                        <li>Стоимость монтажных работ;</li>
                        <li>Стоимость настройки ПО и оборудования.</li>
                    </ul>
                </div>

                <span id="faq5">Как можно обмануть систему?</span>
                <div class="faq5" id="kat" style="display: none;">                
                    <p>
                        Как показывает практика, наши водители достаточно изобретательны в поиске 
                        способа обмануть систему. Но хотелось бы их огорчить, все попытки легко 
                        выявляются в процессе эксплуатации и отображаются в диспетчерском ПО. 
                        Также все возможные соединения пломбируются.
                    </p>
                </div>

                <span id="faq6">Есть ли перерывы в работе системы?</span>
                <div class="faq6" id="kat" style="display: none;">
                    <p>
                        Система GPS/ГЛОНАСС мониторинга компании «Ставтрэк» работает круглосуточно без выходных и перерывов.
                    </p>
                </div>

                <span id="faq7">Как долго хранится информация на сервере?</span>
                <div class="faq7" id="kat" style="display: none;">
                    <p>
                        Информация о транспортных средствах хранится на сервере 1 год с момента установки.
                    </p>
                </div>

                <span id="faq8">Что происходит при потере сигнала GSM?</span>
                <div class="faq8" id="kat" style="display: none;">
                    <p>
                        У GPS/ГЛОНАСС терминала есть внутренняя память «черный ящик», где сохраняется 
                        полученная со спутников информация и выгружается на сервер при появлении сигнала GSM.
                    </p>
                </div>

                <span id="faq9">На какой территории работает система «Арттрэк»?</span>
                <div class="faq9" id="kat" style="display: none;">
                    <p>
                        Наша система спутникового мониторинга работает на всей территории Российской Федерации.
                    </p>
                </div>

                <span id="faq10">На какие виды техники возможна установка систем спутникового контроля?</span>
                <div class="faq10" id="kat" style="display: none;">
                    <p>
                        Систему спутникового мониторинга «Ставтрэк» можно устанавливать на все виды импортной и отечественной техники
                    </p>
                </div>

                <span id="faq11">Возникают ли проблемы в работе двигателя после монтажа датчиков уровня топлива?</span>
                <div class="faq11" id="kat" style="display: none;">
                    <p>
                        Проблем в работе двигателя не возникает, потому что датчик уровня топлива монтируется в 
                        топливный бак и никак не нарушает топливную систему транспортного средства.
                    </p>
                </div>

                <span id="faq12">Какова погрешность высокоточного датчика уровня топлива LLS?</span>
                <div class="faq12" id="kat" style="display: none;">
                    <p>
                        Производитель (Omnicomm) заявляет погрешность 1%
                    </p>
                </div>

<!--                <span id="faq13">Как работает спутниковый мониторинг транспорта?</span>
                <div class="faq13" id="kat" style="display: none;">
                    <p>Более подробную информацию Вы сможете посмотреть Здесь:</p>
                    <ul class="marker">
                        <li><a href="<?php
                            echo $this->url(
                                    array(
                                'controller' => 'help',
                                'action' => 'howwork'
                                    ), 'default', true)
                            ?>">Схема работы;</li>
                        <li>GPS мониторинг;</li>
                        <li>Глонасс мониторинг;</li>
                        <li>Контроль топлива.<//li>
                    </ul>
                </div>-->
            </div>

        </div>

    </div>
</div>

<script>
    $('.faq1').css("display", "block");

    $('#faq1').click(function() {
        $('.faq1').slideToggle()
                .siblings("#kat:visible").slideUp("slow");
    });

    $('#faq2').click(function() {
        $('.faq2').slideToggle()
                .siblings("#kat:visible").slideUp("slow");
    });

    $('#faq3').click(function() {
        $('.faq3').slideToggle()
                .siblings("#kat:visible").slideUp("slow");
    });

    $('#faq4').click(function() {
        $('.faq4').slideToggle()
                .siblings("#kat:visible").slideUp("slow");
    });

    $('#faq5').click(function() {
        $('.faq5').slideToggle()
                .siblings("#kat:visible").slideUp("slow");
    });

    $('#faq6').click(function() {
        $('.faq6').slideToggle()
                .siblings("#kat:visible").slideUp("slow");
    });

    $('#faq7').click(function() {
        $('.faq7').slideToggle()
                .siblings("#kat:visible").slideUp("slow");
    });

    $('#faq8').click(function() {
        $('.faq8').slideToggle()
                .siblings("#kat:visible").slideUp("slow");
    });

    $('#faq9').click(function() {
        $('.faq9').slideToggle()
                .siblings("#kat:visible").slideUp("slow");
    });

    $('#faq10').click(function() {
        $('.faq10').slideToggle()
                .siblings("#kat:visible").slideUp("slow");
    });

    $('#faq11').click(function() {
        $('.faq11').slideToggle()
                .siblings("#kat:visible").slideUp("slow");
    });

    $('#faq12').click(function() {
        $('.faq12').slideToggle()
                .siblings("#kat:visible").slideUp("slow");
    });

    $('#faq13').click(function() {
        $('.faq13').slideToggle()
                .siblings("#kat:visible").slideUp("slow");
    });



</script>