<div class="container">
    <div class="text_block" >
        <h3 class="title">Схема работы GPS/ГЛОНАСС мониторинга</h3>
        <div class="text_caption">
            <div class="howwork">
                <div id="glonass" class="how_glonass">
                    <img src="/img/more.png">
                    <div class="howglonass_text">Приём GPS/ГЛОНАСС сигнала
                    </div>
                </div>
                
                <div id="gsm" class="how_gsm">
                    <img src="/img/more.png">
                    <div class="howgsm_text">Передача данных по GSM
                    </div>
                </div>
                
                <div id="monitor" class="how_monitor">
                    <img src="/img/more.png">
                    <div class="howmonitor_text">GPS/ГЛОНАСС трекер
                    </div>
                </div>
                
                <div id="board" class="how_board">
                    <img src="/img/more.png">
                    <div class="howboard_text">Дополнительные датчики
                    </div>
                </div>
                
                <div id="plant" class="how_plant">
                    <img src="/img/more.png">
                    <div class="howplant_text">Датчик расхода топлива
                    </div>
                </div>
                
                <div id="couch" class="how_couch">
                    <img src="/img/more.png">
                    <div class="howcouch_text">Датчик уровня топлива
                    </div>
                </div>

                <div id="gl_text" class="slowtogle">
                    <a href="" class="btn btn-danger close gps_close" title="Закрыть"><i class="icon-remove"></i></a>
                    <img src="/img/gps-super-shema.jpg">
                    <p>
                        Внешняя ГЛОНАСС/GPS антенна постоянно принимает сигнал со спутников. 
                        По этому сигналу трекер определяет точные координаты своего местонахождения. 
                        Эта информация, а также данные с различных датчиков установленных на транспорте, 
                        собираются в памяти трекера для дальнейшей передачи на сервер мониторинга автотранспорта...
                    </p>

                </div>
                
                <div id="gsm_text" class="slowtogle">
                    <a href="" class="btn btn-danger close gsm_close" title="Закрыть"><i class="icon-remove"></i></a>
                    <img src="/img/gsm-super-shema.jpg">
                    <p>
                        Через внешнюю GSM антенну данные из трекера посредством GPRS соединения 
                        передаются на сервер мониторинга Wialon , где она и хранится в дальнейшем. 
                        Диспетчер, ведущий мониторинг своего автопарка может легко получить абсолютно 
                        все данные с сервера. Достаточно подключится к интернету через любое устройство 
                        (ноутбук, компьютер, планшет, телефон) и выйти на специальный веб сайт Wialon. 
                        Здесь пользователю доступны множество отчётов и срезов о работе всего транспорта
                        на предприятии.
                    </p>

                </div>
                
                <div id="monitor_text" class="slowtogle">
                    <a href="" class="btn btn-danger close monitor_close" title="Закрыть"><i class="icon-remove"></i></a>
                    <img src="/img/tracker-super-shema.jpg">
                    <p>
                        Трекер – цифровой терминал для приёма и передачи данных. 
                        Он собирает всевозможную информацию: местоположение, 
                        направление движения, скорость, уровень топлива и т.д. 
                        Трекер состоит из: GPS или ГЛОНАСС приёмника ; GSM передатчика; 
                        разъёмов для подключения датчиков контроля , внешних GPS/ГЛОНАСС и GSM антенн. 
                        Также он имеет внутренюю память и встроенный аккумулятор.
                    </p>

                </div>
                
                <div id="board_text" class="slowtogle">
                    <a href="" class="btn btn-danger close board_close" title="Закрыть"><i class="icon-remove"></i></a>
                    <img src="/img/dopt-datchiki-super-shema.jpg">
                    <p>
                        Датчики работы механизмов - цифровые или аналоговые устройства для передачи 
                        информации о работе дополнительных агрегатов транспортных средств. 
                        Используется в системе GPS/ГЛОНАСС мониторинга транспорта. 
                        Позволяет знать сколько времени работал механизм, где работал, 
                        какой пробег был со включенным механизмом, сколько литров топлива 
                        было потрачено за каждый час работы.
                    </p>

                </div>
                
                <div id="plant_text" class="slowtogle">
                    <a href="" class="btn btn-danger close plant_close" title="Закрыть"><i class="icon-remove"></i></a>
                    <img src="/img/rashodomer-super-shema.jpg">
                    <p>
                        Принцип работы датчика расхода топлива основан на измерении количества топлива, 
                        которое протекает через измерительную камеру расходомера. 
                        Топливо поступает в измерительную камеру через входное отверстие и поворачивает кольцо камеры.
                        Такой датчик может работать автономно или же его можно подключить к общей 
                        системе мониторинга к GPS/GLONASS трекеру...
                    </p>

                </div>
                
                <div id="couch_text" class="slowtogle">
                    <a href="" class="btn btn-danger close couch_close" title="Закрыть"><i class="icon-remove"></i></a>
                    <img src="/img/dut-super-shema.jpg">
                    <p>
                        В наших системах мониторинга применяются высокоточные датчики уровня топлива 
                        от мирового лидера компании Omnicomm. Датчик относится к ёмкостному типу т.е. 
                        он постоянно следит за уровнем топлива в баке и при малейшем его изменении данные 
                        передаются терминалу (трекеру) который в свою очередь отправляет всю информацию 
                        в базу данных на сервер Wialon.
                    </p>

                </div>
            </div>
        </div>

    </div>
</div>

<script>
    $('.how_glonass').hover(function() {
        $('.howglonass_text').slideToggle();
    })
    $('.how_glonass').click(function() {
        $('#gl_text').slideToggle();
        $('#glonass').css('display', 'none');
        $('#monitor').css('display', 'none');
        $('#gsm').css('display', 'none');
        $('#board').css('display', 'none');
        $('#plant').css('display', 'none');
        $('#couch').css('display', 'none');
    })
    $('.gps_close').click(function() {
        $('#gl_text').slideToggle();
        $('.howglonass_text').css('display', 'none');
        $('#glonass').css('display', 'block');
        $('#gsm').css('display', 'block');
        $('#monitor').css('display', 'block');
        $('#board').css('display', 'block');
        $('#plant').css('display', 'block');
        $('#couch').css('display', 'block');
        return false;
    })
    //**************************************
    $('.how_gsm').hover(function() {
        $('.howgsm_text').slideToggle();
    })
    $('.how_gsm').click(function() {
        $('#gsm_text').slideToggle();
        $('#glonass').css('display', 'none');
        $('#monitor').css('display', 'none');
        $('#gsm').css('display', 'none');
        $('#board').css('display', 'none');
        $('#plant').css('display', 'none');
        $('#couch').css('display', 'none');
    })
    $('.gsm_close ').click(function() {
        $('#gsm_text').slideToggle();
        $('.howgsm_text').css('display', 'none');
        $('#glonass').css('display', 'block');
        $('#gsm').css('display', 'block');
        $('#monitor').css('display', 'block');
        $('#board').css('display', 'block');
        $('#plant').css('display', 'block');
        $('#couch').css('display', 'block');
        return false;
    })
    //**************************************
    $('.how_monitor').hover(function() {
        $('.howmonitor_text').slideToggle();
    })
    $('.how_monitor').click(function() {
        $('#monitor_text').slideToggle();
        $('#glonass').css('display', 'none');
        $('#monitor').css('display', 'none');
        $('#gsm').css('display', 'none');
        $('#board').css('display', 'none');
        $('#plant').css('display', 'none');
        $('#couch').css('display', 'none');
    })
    $('.monitor_close ').click(function() {
        $('#monitor_text').slideToggle();
        $('.howmonitor_text').css('display', 'none');
        $('#glonass').css('display', 'block');
        $('#gsm').css('display', 'block');
        $('#monitor').css('display', 'block');
        $('#board').css('display', 'block');
        $('#plant').css('display', 'block');
        $('#couch').css('display', 'block');
        return false;
    })
    //**************************************
    $('.how_board').hover(function() {
        $('.howboard_text').slideToggle();
    })
    $('.how_board').click(function() {
        $('#board_text').slideToggle();
        $('#glonass').css('display', 'none');
        $('#monitor').css('display', 'none');
        $('#gsm').css('display', 'none');
        $('#board').css('display', 'none');
        $('#plant').css('display', 'none');
        $('#couch').css('display', 'none');
    })
    $('.board_close ').click(function() {
        $('#board_text').slideToggle();
        $('.howboard_text').css('display', 'none');
        $('#glonass').css('display', 'block');
        $('#gsm').css('display', 'block');
        $('#monitor').css('display', 'block');
        $('#board').css('display', 'block');
        $('#plant').css('display', 'block');
        $('#couch').css('display', 'block');
        return false;
    })
    //**************************************
    $('.how_plant').hover(function() {
        $('.howplant_text').slideToggle();
    })
    $('.how_plant').click(function() {
        $('#plant_text').slideToggle();
        $('#glonass').css('display', 'none');
        $('#monitor').css('display', 'none');
        $('#gsm').css('display', 'none');
        $('#board').css('display', 'none');
        $('#plant').css('display', 'none');
        $('#couch').css('display', 'none');
    })
    $('.plant_close ').click(function() {
        $('#plant_text').slideToggle();
        $('.howplant_text').css('display', 'none');
        $('#glonass').css('display', 'block');
        $('#gsm').css('display', 'block');
        $('#monitor').css('display', 'block');
        $('#board').css('display', 'block');
        $('#plant').css('display', 'block');
        $('#couch').css('display', 'block');
        return false;
    })
    //**************************************
    $('.how_couch').hover(function() {
        $('.howcouch_text').slideToggle();
    })
    $('.how_couch').click(function() {
        $('#couch_text').slideToggle();
        $('#glonass').css('display', 'none');
        $('#monitor').css('display', 'none');
        $('#gsm').css('display', 'none');
        $('#board').css('display', 'none');
        $('#plant').css('display', 'none');
        $('#couch').css('display', 'none');
    })
    $('.couch_close ').click(function() {
        $('#couch_text').slideToggle();
        $('.howcouch_text').css('display', 'none');
        $('#glonass').css('display', 'block');
        $('#gsm').css('display', 'block');
        $('#monitor').css('display', 'block');
        $('#board').css('display', 'block');
        $('#plant').css('display', 'block');
        $('#couch').css('display', 'block');
        return false;
    })
    
</script>