<div class="container">
    <div class="text_block" >
        <h3 class="title">WIALON: БЫСТРЫЙ СТАРТ</h3>
        <div class="text_caption">
            <div class="service_style">
                <span id="intro">Вход в систему мониторинга</span>
                <div class="intro" id="kat" style="display: none;">
                    <p class="p_link">
                        Перейдя по <a href="http://pro.wialon.com/service.html" target="_blank">этой ссылке</a> 
                        Вы попадете на стартовую страницу WEB приложения Wialon. 
                        Здесь необходимо ввести свое имя пользователя и пароль. Затем нажмите «Войти». 
                        Если у Вас нет логина и пароля то можете войти в демо режим, нажмите ссылку ниже...
                    </p>
                    <img src="/img/wialonstart/vhod.jpg">
                    <p>Поддерживаемыми браузерами являются: Mozilla Firefox 3+, Opera 10.0+, Internet Explorer 8+, Google Chrome 11+.</p>
                </div>
                <span id="interface">Интерфейс</span>
                <div class="interface" id="kat" style="display: none;">
                    <p>
                        Вы вошли в систему мониторинга. Справа отображается карта, а также отчеты и сообщения — 
                        в зависимости от выбранного режима. Слева — рабочая область. 
                        Над рабочей областью располагается переключатель режимов «карта — сообщения — отчеты». 
                        Вкладки на рабочей области могут меняться: «Мониторинг», «Треки», «Мои Места», «Геозоны», 
                        «Уведомления», «Задания» и т.д. Для переключения между вкладками подведите курсор мыши и 
                        выберите нужную из списка.
                    </p>
                    <img src="/img/wialonstart/interface.jpg">
                    <p>
                        Перетягивая карту при помощи мыши, а также масштабируя ее при помощи колеса прокрутки мыши, 
                        переместитесь к месту (городу), которое будет для Вас основным в процессе мониторинга.
                    </p>
                </div>
                <span id="settings">Настройки пользователя</span>
                <div class="settings" id="kat" style="display: none;">
                    <p>
                        Теперь откройте диалог настроек пользователя (ссылка «настройки» в верхней части окна). 
                        Укажите свою временную зону, которая важна для корректного отображения времени в отчетах, 
                        сообщениях, подсказках и т.п.
                    </p>
                    <img src="/img/wialonstart/settings2.png">
                    <p>
                        В этом же диалоге перейдите на вкладку «Карты» и отметьте флажком пункт «Сохранить 
                        координаты и масштаб». Это необходимо для того, чтобы выбранная Вами текущая позиция 
                        карты восстанавливалась при каждом последующем входе в систему. 
                        Когда работа с настройками будет закончена, нажмите «ОК» для сохранения новых настроек.
                    </p>
                    <img src="/img/wialonstart/settings3.png">
                    <p>Подготовительные процедуры окончены. Переходим к созданию объекта мониторинга.</p>
                </div>

                <span id="createobject">Создание объекта</span>
                <div class="createobject" id="kat" style="display: none;">
                    <div class="tabbable"> <!-- Only required for left/right tabs -->
                        <ul class="nav nav-tabs">
                            <li class="active"><a href="#tab11" data-toggle="tab">Шаг 1</a></li>
                            <li><a href="#tab12" data-toggle="tab">Шаг 2</a></li>
                            <li><a href="#tab13" data-toggle="tab">Шаг 3</a></li>
                        </ul>
                        <div class="tab-content">
                            <div class="tab-pane active" id="tab11">
                                <div class="container">
                                    <p>
                                        Перед тем как конфигурировать объект, убедитесь в том, что устройство направлено 
                                        на Wialon. Для этого найдите соответствующий тип устройства в списке 
                                        поддерживаемого оборудования и задайте необходимые параметры.
                                    </p>
                                    <p>
                                        Перейдите на вкладку «Объекты» на рабочей панели и нажмите кнопку 
                                        «Создать объект».
                                    </p>

                                    <img src="/img/wialonstart/new_objekt.png">
                                    <p>
                                        Откроется диалог создания нового объекта. Задайте объекту имя, 
                                        укажите тип используемого оборудования (выберите из списка доступных), 
                                        введите уникальный ID (IMEI или серийный номер) и телефонный номер SIM-карты, 
                                        встроенной в объект.
                                        <img src="/img/wialonstart/objekt-general.png">
                                    </p>
                                </div>
                            </div>
                            <div class="tab-pane" id="tab12">
                                <p>
                                <div class="container">
                                    <p>
                                        На следующей вкладке «Изображение» можно выбрать картинку, которой объект 
                                        будет отображаться на карте. Для этого нажмите на кнопку «Библиотека» и 
                                        выберите из предложенных.
                                    </p>
                                    <img src="/img/wialonstart/objekt-3.jpg">
                                </div>
                                </p>
                            </div>
                            <div class="tab-pane" id="tab13">
                                <p>
                                <div class="container">
                                    <p>
                                        На вкладке «Дополнительно» укажите «Ограничение скорости, км/ч». 
                                        Благодаря этой настройке впоследствии можно будет вывести интервалы 
                                        превышения скорости в соответствующий отчет.
                                    </p>
                                    <img src="/img/wialonstart/objekt-4.png">
                                    <p>В конце нажмите «ОК» для сохранения данных. Созданный объект появится в списке</p>

                                    <img src="/img/wialonstart/objekt-5.png">
                                    <p>Он также появится в рабочей области на панели «Мониторинг».</p>
                                    <img src="/img/wialonstart/objekt-6.png">

                                </div>
                                </p>
                            </div>

                        </div>
                    </div>
                </div>

                <span id="test">Проверка объекта</span>
                <div class="test" id="kat" style="display: none;">                
                    <div class="tabbable"> <!-- Only required for left/right tabs -->
                        <ul class="nav nav-tabs">
                            <li class="active"><a href="#tab21" data-toggle="tab">Журнал</a></li>
                            <li><a href="#tab22" data-toggle="tab">Всплывающая подсказка</a></li>
                            <li><a href="#tab23" data-toggle="tab">Режим сообщений</a></li>
                        </ul>
                        <div class="tab-content">
                            <div class="tab-pane active" id="tab21">
                                <div class="container">
                                    <p>
                                        Если все сделано правильно, после создания объекта данные от него должны начать 
                                        поступать в систему. При поступлении каждого нового сообщения от объекта оно 
                                        отображается в «Журнале». Чтобы просмотреть журнал, нажмите на кнопку в правом 
                                        нижнем углу программы.
                                    </p>
                                    <img src="/img/wialonstart/log1.png">
                                    <p>
                                        Кроме сообщений от объекта, в журнале также регистрируются текущие операции, 
                                        такие как создание и модификация геозон, уведомлений, шаблонов отчетов, 
                                        настроек объектов и т.п.
                                    </p>
                                </div>
                            </div>
                            <div class="tab-pane" id="tab22">
                                <p>
                                <div class="container">
                                    <p>
                                        Отметьте объект в рабочем списке на вкладке «Мониторинг», чтобы увидеть его 
                                        на карте.
                                        <img src="/img/wialonstart/log2.png">
                                        При наведении курсора мыши на объект во всплывающей подсказке отображается 
                                        актуальная информация по объекту: последнее сообщение, положение, скорость и т.п.
                                    </p>
                                    <img src="/img/wialonstart/log3.png">
                                </div>
                                </p>
                            </div>
                            <div class="tab-pane" id="tab23">
                                <p>
                                <div class="container">
                                    <p>
                                        Наиболее надежный способ проверки работоспособности объекта — 
                                        просмотр сообщений от него. Чтобы перейти в режим сообщений, 
                                        щелкните по ссылке «сообщения» над рабочей областью на панели 
                                        переключения режимов. Выберите интервал, за который хотите получить сообщения, 
                                        и нажмите «Выполнить».
                                    </p>
                                    <p>
                                        В таблице можно оценить, какие сообщения от объекта поступили в систему 
                                        и какие данные в них содержатся. Кроме того, на карте будет показан трек 
                                        движения за заданный период.
                                    </p>

                                    <img src="/img/wialonstart/log-messages.jpg">

                                </div>
                                </p>
                            </div>

                        </div>
                    </div>
                </div>

                <span id="creategeo">Создание геозон</span>
                <div class="creategeo" id="kat" style="display: none;">
                    <p>
                        В местах, которые представляют повышенный интерес и должны попадать под какой-нибудь вид контроля, 
                        рекомендуется создавать геозоны. Для этого перейдите на вкладку «Геозоны» и нажмите на кнопку 
                        «Создать геозону».
                    </p>
                    <img src="/img/wialonstart/geozone1.png">
                    <p>
                        Наиболее простой и быстрый для создания тип геозоны — круг с заданным радиусом. 
                        Введите название будущей геозоны, выберите тип «круг», сделайте двойной щелчок левой 
                        кнопкой мыши по карте в месте предполагаемой геозоны, при необходимости откорректируйте 
                        радиус и цвет и нажмите «Сохранить».
                    </p>
                    <img src="/img/wialonstart/geozone2.jpg">              
                </div>

                <span id="settingsnotife">Настройка уведомления</span>
                <div class="settingsnotife" id="kat" style="display: none;">
                    <p>
                        Теперь создадим уведомление о входе в геозону. Перейдите на вкладку «Уведомления» и 
                        нажмите «Создать уведомление».
                    </p>
                    <img src="/img/wialonstart/warning1.png">
                    <p>
                        Перемещаясь по диалогу от страницы к странице при помощи кнопки «Далее», 
                        задайте следующие параметры для работы уведомления:
                    </p>
                    <ul class="marker">
                        <li>Выберите свой объект (отметьте его флажком).</li>
                        <li>Выберите тип контроля (пункт «Контроль геозоны»).</li>
                        <li>Укажите тип проверки (пункт «Контролировать вход в геозону») и выберите нужную геозону из списка (кликните по ней). Для выбора нескольких геозон зажмите клавишу на клавиатуре.</li>
                        <li>Оставьте тот текст уведомления, которые предлагается по умолчанию.</li>
                        <li>Выберите способ доставки уведомления, например, «Отобразить онлайн уведомление во всплывающем окне».</li>
                        <li>Введите название уведомления.</li>
                        <li>В конце нажмите «ОК».</li>
                    </ul>
                    <img src="/img/wialonstart/warning2.jpg">
                    <p>При срабатывании уведомление появится в правом верхнем углу окна программы.</p>
                </div>

                <span id="support">Отчеты</span><br />
                <div class="support" id="kat" style="display: none;">
                    <div class="tabbable"> <!-- Only required for left/right tabs -->
                        <ul class="nav nav-tabs">
                            <li class="active"><a href="#tab31" data-toggle="tab">Добавить</a></li>
                            <li><a href="#tab32" data-toggle="tab">Геозоны</a></li>
                            <li><a href="#tab33" data-toggle="tab">Скорость</a></li>
                            <li><a href="#tab34" data-toggle="tab">График</a></li>
                            <li><a href="#tab35" data-toggle="tab">Сохранить</a></li>
                            <li><a href="#tab36" data-toggle="tab">Экспорт</a></li>
                        </ul>
                        <div class="tab-content">
                            <div class="tab-pane active" id="tab31">
                                <div class="container">
                                    <p>
                                        Переход в режим отчетов осуществляется при помощи переключателя режимов 
                                        над рабочей областью. Перейдите в режим отчетов и нажмите кнопку «Создать». 
                                        Мы создадим шаблон, который будет содержать две таблицы (по посещению геозон 
                                        и по превышению скорости) и один график.
                                    </p>
                                    <img src="/img/wialonstart/otchotyi1.jpg">
                                    
                                </div>
                            </div>
                            <div class="tab-pane" id="tab32">                                
                                <div class="container">
                                    <p>
                                        Нажмите «Добавить таблицу» и выберите тип таблицы «Геозоны». 
                                        Слева отметьте флажками столбцы, которые должны присутствовать в таблице. 
                                        Справа выберите геозону(ы). Нажмите «ОК».
                                    </p>
                                    <img src="/img/wialonstart/otchetyi2.png">
                                </div>
                            </div>
                            <div class="tab-pane" id="tab33">
                                <div class="container">
                                    <p>
                                        Далее добавим таблицу типа «Превышение скорости». Для ее формирования в 
                                        свойствах объекта мы устанавливали параметр «Ограничение скорости». 
                                        В дополнительных параметрах укажем, что нам необходимы превышения, 
                                        которые длились не менее одной минуты. Нажмите «ОК».
                                    </p>
                                    
                                    <img src="/img/wialonstart/otchetyi3.png">

                                </div>
                            </div>
                            <div class="tab-pane" id="tab34">
                                <div class="container">
                                    <p>
                                        Теперь нажмите кнопку «Добавить график» и отметьте флажком нужный вид графика.
                                        (Учтите, что для формирования многих видов графиков необходимы 
                                        соответствующие датчики.) Нажмите «ОК»
                                    </p>
                                    <img src="/img/wialonstart/otchetyi4.png">
                                    
                                </div>
                            </div>
                            <div class="tab-pane" id="tab35">
                                <div class="container">
                                    <p>
                                        Вот что должно получиться. Осталось дать шаблону имя и сохранить его.
                                    </p>
                                    <img src="/img/wialonstart/otchetyi5-1.png">
                                    <p>
                                        Для получения отчета в рабочей области задайте параметры: 
                                        выберите объект, шаблон, отчетный интервал. Нажмите «Выполнить».
                                    </p>
                                    <img src="/img/wialonstart/otchetyi5-2.png">
                                </div>
                            </div>
                            <div class="tab-pane" id="tab36">
                                <div class="container">
                                    <p>
                                        Сгенерированный отчет появится справа. Между разделами отчета 
                                        (таблицами и графиками) можно переключаться при помощи навигационной 
                                        панели слева. Кроме того, отчет может быть экспортирован в файл и 
                                        сохранен на диск или распечатан (кнопки «Экспорт в файл» и «Печать»).
                                    </p>
                                    
                                    <img src="/img/wialonstart/otchetyi6-1.png">
                                    <img src="/img/wialonstart/otchetyi6-2.png">
                                    <img src="/img/wialonstart/otchetyi6-3.png">

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>

    </div>
</div>

<script>
    $('.intro').css("display", "block");

    $('#intro').click(function() {
        $('.intro').slideToggle()
                .siblings("#kat:visible").slideUp("slow");
    });

    $('#interface').click(function() {
        $('.interface').slideToggle()
                .siblings("#kat:visible").slideUp("slow");
    });
    $('#settings').click(function() {
        $('.settings').slideToggle()
                .siblings("#kat:visible").slideUp("slow");
    });
    $('#createobject').click(function() {
        $('.createobject').slideToggle()
                .siblings("#kat:visible").slideUp("slow");
    });
    $('#test').click(function() {
        $('.test').slideToggle()
                .siblings("#kat:visible").slideUp("slow");
    });
    $('#creategeo').click(function() {
        $('.creategeo').slideToggle()
                .siblings("#kat:visible").slideUp("slow");
    });
    $('#settingsnotife').click(function() {
        $('.settingsnotife').slideToggle()
                .siblings("#kat:visible").slideUp("slow");
    });
    $('#support').click(function() {
        $('.support').slideToggle()
                .siblings("#kat:visible").slideUp("slow");
    });

</script>