<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>ART-TRACK</title>
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
        <script src="/js/bootstrap.min.js"></script>
        <?php echo $this->headLink()->appendStylesheet('/css/bootstrap.min.css') ?> 
        <?php echo $this->headLink()->appendStylesheet('/css/style.css') ?>        
        <link href='http://fonts.googleapis.com/css?family=Oranienbaum' rel='stylesheet' type='text/css'>
            <link href='http://fonts.googleapis.com/css?family=Exo+2&subset=latin,cyrillic' rel='stylesheet' type='text/css' />
    </head>

    <body>
        <div class="header_line">
            <div class="container">
                <div class="row head_margin">
                    <div class="span2">
                        <a href="#" class="btn btn-custom">Мониторинг</a>
                    </div>
                    <div class="span4 offset2">
                        <div class="header_phone">8(800) 500-17-14</div>
                        <div class="header_text">Звонок по России бесплатный</div>
                    </div>
                    <div class="span3 offset1">
                        <div class="row">
                            <div class="span1"><img src="/img/mini_map.png"></div>
                            <div class="span2"><span class="header_city">Ваш город:</span> 
                                <a href="#" class="select_city">Ставрополь</a></div>
                        </div>
                    </div>
                </div>
            </div><!--container-->
        </div><!--header_line-->
        <!--*************************************************************end header line-->
        <div class="container">
            <div class="row header_opacity">
                <div class="span4">
                    <div class="link_menu_left">
                        <a href="#">О компании</a><br /><br />
                        <a href="#">Новости</a>
                    </div>
                </div>
                <div class="span4">
                    <img src="../img/logo.png" class="logo" />
                </div>
                <div class="span4">
                    <div class="link_menu_right">
                        <a href="#">Франчайзинг</a><br /><br />
                        <a href="#">Техподдержка</a>
                    </div>
                </div>
            </div>
        </div>
        <?php echo $this->layout()->content ?>

    </body>
</html>
