<!DOCTYPE HTML>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <?php echo $this->headLink()->appendStylesheet('/css/bootstrap.min.css') ?> 
        <?php echo $this->headLink()->appendStylesheet('/css/style.css') ?>   
        <?php echo $this->headLink()->appendStylesheet('/css/admin.css') ?>   
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
    </head>

    <body>
        <? if (@$_COOKIE['admin'] == '') : ?>
        <form method="POST" action="/admin/users/">
                <label><input type="text" name="login" placeholder="Login" class="input-large"></label>
                <label><input type="password" name="pass" placeholder="Password" class="input-large"></label>
                <input type="submit" name="input" value="Войти" class="button_s button_login">
            </form>
        <? else : ?>
            <div style="margin: 10px 50px;">
                <div id="add_data">
                    <h2>Добавление данных на сайт</h2>
                    <div class="tabbable"> <!-- Only required for left/right tabs -->
                        <ul class="nav nav-tabs">
                            <li class="active"><a href="#adtab11" data-toggle="tab">Новости</a></li>
                            <li><a href="#adtab12" data-toggle="tab">Города</a></li>
                            <!--<li><a href="#adtab13" data-toggle="tab">Акции</a></li>-->
                        </ul>
                        <div class="tab-content">
                            <div class="tab-pane active" id="adtab11">
                                <a href="#" class="add_news">Добавить новость</a>
                                <div id="add_new_news">
                                    <form method="POST" action="/admin/users/" enctype="multipart/form-data">
                                        <label><input type="text" name="title" placeholder="Заголовок" class="input-xxlarge"></label>
                                        <label><textarea name="text" placeholder="Текст" ></textarea></label>
                                        <label><input type="file" name="img" accept="image/*"></label>
                                        <input type="submit" name="addnews" value="Добавить" class="button_s button_add_news">
                                    </form>
                                </div>
                                <h3>Новости</h3>
                                <table class="table table-striped table-bordered table-condensed" id="news">
                                    <tr>
                                        <th>ID</th>
                                        <th>Заголовок</th>
                                        <th>Текст</th>
                                        <th>Изображение</th>
                                    </tr>
                                    <? foreach ($this->news as $news) : ?>
                                        <tr>
                                            <td><?= $news['id']; ?></td>
                                            <td><?= $news['title']; ?></td>
                                            <td><?= $news['text']; ?></td>
                                            <td><?= $news['img']; ?></td>
                                            <td><a href="#" class="news_delete" data-id="<?= $news['id']; ?>" title="Удалить"><i class="icon-remove"></i></a></td>
                                        </tr>
                                    <? endforeach; ?>

                                </table>
                            </div>
                            <div class="tab-pane" id="adtab12">
                                <a href="#" class="add_city">Добавить новый</a>
                                <div id="add_new_city">
                                    <form method="POST">
                                        <label><input type="text" name="name" placeholder="Название" class="input-xxlarge"></label>
                                        <label><input type="text" name="addres" placeholder="Адрес" class="input-xxlarge"></label>
                                        <label><input type="text" name="phone" placeholder="Телефон" class="input-xxlarge"></label>
                                        <label><input type="email" name="email" placeholder="Email" class="input-xxlarge"></label>
                                        <label><input type="text" name="yandex" placeholder="Yandex" class="input-xxlarge"></label>
                                        <a href="#" class="button_s button_add_city">Добавить</a>
                                    </form>
                                </div>
                                <h3>Города</h3>
                                <table class="table table-striped table-bordered table-condensed" id="city">
                                    <tr>
                                        <th>ID</th>
                                        <th>Название</th>
                                        <th>Адрес</th>
                                        <th>Телефон</th>
                                        <th>Email</th>
                                        <th>Yandex</th>
                                        <th>Действия</th>
                                    </tr>
                                    <? foreach ($this->cities as $cities) : ?>
                                        <tr>
                                            <td><?= $cities['id']; ?></td>
                                            <td><?= $cities['name']; ?></td>
                                            <td><?= $cities['addres']; ?></td>
                                            <td><?= $cities['phone']; ?></td>
                                            <td><?= $cities['email']; ?></td>
                                            <td><?= $cities['yandex']; ?></td>
                                            <td><a href="#" class="city_delete" title="Удалить"><i class="icon-remove"></i></a></td>
                                        </tr>
                                    <? endforeach; ?>

                                </table>
                            </div>
                            <!--                        <div class="tab-pane" id="adtab13">
                                                        <h3>Акции</h3>
                            
                                                    </div>-->

                        </div>
                    </div>
                </div>
            </div>
        <? endif; ?>
        <script src="/js/bootstrap.min.js"></script>
        <script src="/js/admin.js"></script>
    </body>
</html>