
<div class="container">
    <div class="text_block" >
        <h3 class="title">Курсоуказатели</h3>
        <div class="text_caption">
            <p>
                Ни для кого не секрет, что в сельском хозяйстве особенно актуальным является подбор 
                <strong>высококвалифицированных кадров</strong>. Уже проверенные временем уходят на заслуженный отдых, 
                а молодежь не торопиться возвращаться домой, после обучения в ВУЗах.
            </p>
            <p>
                Но а если все-таки возвращаются, на обучение, набор необходимого навыка уходит много времени, 
                плюс к этому из-за неквалифицированной работы несет убытки предприятие. 
                Решить эту, но и многие другие проблемы могут курсоуказатели от культовой компании Trimbe (Тримбл)!
            </p>
            <p><em>Задачи, решаемые установкой системы параллельного вождения:</em></p>
            <ul class="marker">
                <li>обеспечение возможности работы при недостаточной видимости (ночью, в тумане, пыли);</li>
                <li>полный отказ от сигнальщиков и от использования маркеров;</li>
                <li>снижение расхода семенного материала, ГСМ и минеральных удобрений;</li>
                <li>сокращение времени выполнения работ;</li> 
                <li>обмер сельскохозяйственных площадей.</li>     
            </ul>
            <img src="/img/equipment/kursoroukazatel/kursoukazatel.jpg" class="img_eq" alt="Устройство курсороуказателя" title="Устройство курсороуказателя">
            <p><em>Устроен курсоуказатель очень просто:</em></p>
            <ul class="marker">
                <li>
                    1 - Светодиоды в автономном режиме. При нахождении транспортного средства на линии, 
                    горят три центральных светодиода. При отклонении от курса светодиоды перемещаются в сторону;
                </li>
                <li>2 - Функциональные кнопки, выполняющие функции, указанные иконками;</li>
                <li>3 - Линии полос. Полоса текущего движения - красная, соседние полосы - синие.</li>
                <li>4 - Помощь и подсказки. Справочная по использованию системы;</li> 
                <li>
                    5 - Иконка транспортного средства. 
                    Отображает положение транспортного средства и направление движения относительно текущей полосы;
                </li>     
                <li>
                    6 - Отображение зоны покрытия и перекрытий. 
                    Покрытие выводится на экран при включенной клавише опрыскивателя, 
                    при включённой клавише зоны покрытия или при подключении автоматического подруливающего устройства;
                </li>     
                <li>7 - Кнопки: OK, Up (вверх), Down (вниз). Кнопка со стрелкой отмечает иконку, кнопка ОК выбирает её.</li>     
                <li>8 - ESC кнопка (на оборотной стороне).Позволяет отменить изменения и поднимает меню на уровень вверх.</li>     
            </ul>
            <p>
                Курсоуказатель прост в работе! Обучение механизатора в среднем занимает <strong>30 минут</strong>. 
                Возраст тоже не проблема: интуитивно понятный интерфейс, 
                русскоязычное меню позволит полностью освоить принцип работы за день и , 
                в дальнейшем, многие отказываются работать без навигации.
            </p>
            <p class="p_link">
                Так же к <a href="<?php
                echo $this->url(
                        array(
                    'controller' => 'industry',
                    'action' => 'parallels'
                        ), 'default', true)
                ?>">системе параллельного вождения</a> можно подключить подруливающее устройство, 
                либо систему автопилотирования. Это позволит работать с высокой точностью 
                ( <strong>до 2.5 сантиметров в междурядье</strong> ) и полностью исключить ошибки механизатора.
            </p> 

            <h4>Купить курсоуказатель:</h4>
            <p>
                Протестировав большое количество моделей различного производства 
                (Россия, Европа, Китай, США) мы готовы предложить Вам лучшее! 
                Эти приборы выведут технологию точного земледелия на новый уровень.
            </p>

            <div class="trackers">
                <div style="position: relative;">
                    <a href="<?php
                    echo $this->url(
                            array(
                        'controller' => 'equipment',
                        'action' => 'kursoroukazatel1'
                            ), 'default', true)
                    ?>"><img src="/img/equipment/kursoroukazatel/trimble-ez-guide250.jpg" class="img_n" style="height: 169px;"></a>
                </div>
                <div class="tracker_text">
                    <p><a href="<?php
                        echo $this->url(
                                array(
                            'controller' => 'equipment',
                            'action' => 'kursoroukazatel1'
                                ), 'default', true)
                        ?>">Курсоуказатель: <br />Trimble EZ-Guide 250</a></p>
                    <p class="buttons">
                        
                    </p>
                </div>
            </div>

            <div class="trackers">
                <div style="position: relative;">
                    <a href="<?php
                    echo $this->url(
                            array(
                        'controller' => 'equipment',
                        'action' => 'kursoroukazatel2'
                            ), 'default', true)
                    ?>"><img src="/img/equipment/kursoroukazatel/trimble-ag-gps-fmx.jpg" class="img_n" style="height: 169px;"></a>
                </div>
                <div class="tracker_text">
                    <p><a href="<?php
                        echo $this->url(
                                array(
                            'controller' => 'equipment',
                            'action' => 'kursoroukazatel2'
                                ), 'default', true)
                        ?>">Курсоуказатель: <br />Trimble AgGPS FmX</a></p>
                    <p class="buttons">
                        
                    </p>
                </div>
            </div>

            <div class="trackers">
                <div style="position: relative;">
                    <a href="<?php
                    echo $this->url(
                            array(
                        'controller' => 'equipment',
                        'action' => 'kursoroukazatel3'
                            ), 'default', true)
                    ?>"><img src="/img/equipment/kursoroukazatel/trimble-cfx-750.jpg" class="img_n" style="height: 169px;"></a>
                </div>
                <div class="tracker_text">
                    <p><a href="<?php
                        echo $this->url(
                                array(
                            'controller' => 'equipment',
                            'action' => 'kursoroukazatel3'
                                ), 'default', true)
                        ?>">Курсоуказатель: <br />Trimble CFX-750</a></p>
                    <p class="buttons">
                        
                    </p>
                </div>
            </div>

            <h4>Внимание! Для оформления заказа звоните на бесплатную горячую линию: </h4>
            <h4>8(800) 500-17-14</h4>
        </div>

    </div>
</div>