
<div class="container">
    <div class="text_block" >
        <h3 class="title">Динамик внешний DM-250</h3>
        <div class="text_caption">
            <div class="row">
                <div class="span5">
                    <img src="/img/equipment/options/dm-250_thumb.jpg" class="img_view">
                </div>
                <div class="span6">
                    <p class="buttons">
                        <a href="#" class="button_b">Купить Динамик внешний DM-250</a>
                        <a href="#" class="button_s">Цена на Динамик внешний DM-250</a>
                    </p>
                    <h4>А так же для оформления заказа звоните на бесплатную горячую линию: 8(800) 500-17-14</h4>

                </div>
            </div>
            <p>
                Динамик DM-250 для автомобильных радиостанций отличается своими компактными размерами 77x65x40 мм.
                Кабель длинной 1.8 метра позволит разместить динамик в удобном для вас месте.
            </p>
            <p><h4>Особенности динамика DM-250</h4></p>            
            <ul class="marker">
                <li>Мощность 5 Вт
                <li>Сопротивление 8 Ом
                <li>Разъем 3,5 мм моно  
                <li>Габариты 77x65x40 мм  
                <li>Длина кабеля 1,8 метра
            </ul>

            <p><h4>Характеристики:</h4></p>  
            <ul class="marker">
                <li>Рамеры, мм  77x65x40
                <li>Длина кабеля, м	1,8
            </ul>

            <p><h4>Комплект поставки:</h4></p> 
            <ul class="marker">
                <li>Динамик
                <li>Скоба крепления
                <li>Кронштейн для крепления с болтами
            </ul>
        </div>

    </div>
</div>