
<div class="container">
    <div class="text_block" >
        <h3 class="title">Антенна GPS/ГЛОНАСС</h3>
        <div class="text_caption">
            <div class="row">
                <div class="span5">
                    <img src="/img/equipment/options/antena-gps-glonass.jpg" class="img_view">
                </div>
                <div class="span6">
                    <p class="buttons">
                        <a href="#" class="button_b">Купить Антенна GPS/ГЛОНАСС</a>
                        <a href="#" class="button_s">Цена на Антенна GPS/ГЛОНАСС</a>
                    </p>
                    <h4>А так же для оформления заказа звоните на бесплатную горячую линию: 8(800) 500-17-14</h4>

                </div>
            </div>
            <p>
                Предназначена для приема навигационных сигналов спутниковых навигационных систем GPS (США) и ГЛОНАСС (Россия).
            </p>
        </div>

    </div>
</div>