
<div class="container">
    <div class="text_block" >
        <h3 class="title">Аккумуляторная батарея 1100 mAh</h3>
        <div class="text_caption">
            <div class="row">
                <div class="span5">
                    <img src="/img/equipment/options/battery-1100mah.jpg" class="img_view">
                </div>
                <div class="span6">
                    <p class="buttons">
                        <a href="#" class="button_b">Купить Аккумуляторная батарея 1100 mAh</a>
                        <a href="#" class="button_s">Цена на Аккумуляторная батарея 1100 mAh</a>
                    </p>
                    <h4>А так же для оформления заказа звоните на бесплатную горячую линию: 8(800) 500-17-14</h4>

                </div>
            </div>
            <p>
                Аккумуляторная батарея 1100 mAh позволит терминалу работать в автономном режиме 8-10 часов.
            </p>
        </div>

    </div>
</div>