
<div class="container">
    <div class="text_block" >
        <h3 class="title">Дополнительные опции</h3>
        <div class="text_caption">
            <h4>Кроме основного оборудования для мониторинга, Мы предлагаем различные дополнительные опции и аксессуары:</h4>

            <div class="trackers">
                <div style="position: relative;">
                    <a href="#"><img src="/img/equipment/options/tangenta-vector-hm-44.jpg" class="img_n" style="height: 187px;"></a>
                </div>
                <div class="tracker_text">
                    <p><a href="#">Опция: <br />Тангента Vector HM-44</a></p>
                    <p class="buttons">
                        <a href="#" class="button_b">Купить</a>
                        <a href="#" class="button_s">Цена</a>
                    </p>
                </div>
            </div>

            <div class="trackers">
                <div style="position: relative;">
                    <a href="#"><img src="/img/equipment/options/dm-250_thumb.jpg" class="img_n" style="height: 187px;"></a>
                </div>
                <div class="tracker_text">
                    <p><a href="#">Опция: Динамик внешний DM-250</a></p>
                    <p class="buttons">
                        <a href="#" class="button_b">Купить</a>
                        <a href="#" class="button_s">Цена</a>
                    </p>
                </div>
            </div>

            <div class="trackers">
                <div style="position: relative;">
                    <a href="#"><img src="/img/equipment/options/antena-gps-glonass.jpg" class="img_n" style="height: 187px;"></a>
                </div>
                <div class="tracker_text">
                    <p><a href="#">Опция: <br />Антенна GPS/ГЛОНАСС</a></p>
                    <p class="buttons">
                        <a href="#" class="button_b">Купить</a>
                        <a href="#" class="button_s">Цена</a>
                    </p>
                </div>
            </div>

            <div class="trackers">
                <div style="position: relative;">
                    <a href="#"><img src="/img/equipment/options/antena-gsm.jpg" class="img_n" style="height: 187px;"></a>
                </div>
                <div class="tracker_text">
                    <p><a href="#">Опция: <br />Антенна GSM</a></p>
                    <p class="buttons">
                        <a href="#" class="button_b">Купить</a>
                        <a href="#" class="button_s">Цена</a>
                    </p>
                </div>
            </div>

            <div class="trackers">
                <div style="position: relative;">
                    <a href="#"><img src="/img/equipment/options/battery-1100mah.jpg" class="img_n" style="height: 187px;"></a>
                </div>
                <div class="tracker_text">
                    <p><a href="#">Опция: Аккумуляторная батарея 1100 mAh</a></p>
                    <p class="buttons">
                        <a href="#" class="button_b">Купить</a>
                        <a href="#" class="button_s">Цена</a>
                    </p>
                </div>
            </div>

            <h4>Внимание! Для оформления заказа звоните на бесплатную горячую линию: </h4>
            <h4>8(800) 500-17-14</h4>
        </div>

    </div>
</div>