
<div class="container">
    <div class="text_block" >
        <h3 class="title">Тангента Vector HM-44</h3>
        <div class="text_caption">
            <div class="row">
                <div class="span5">
                    <img src="/img/equipment/options/tangenta-vector-hm-44.jpg" class="img_view">
                </div>
                <div class="span6">
                    <p class="buttons">
                        <a href="#" class="button_b">Купить Тангента Vector HM-44</a>
                        <a href="#" class="button_s">Цена на Тангента Vector HM-44</a>
                    </p>
                    <h4>А так же для оформления заказа звоните на бесплатную горячую линию: 8(800) 500-17-14</h4>

                </div>
            </div>
            <p>
                Тангента Vector HM-44 для портативных радиостанций. Оснащена светодиодной индикацией вызова и кнопкой “РТТ” Предусмотрено крепление с помощью 
                прищепки на удобное для пользователя место.Разъём тангенты Vector HM-44 крепится к радиостанции с помощью винта, что исключает случайное отключение от радиостанции.
            </p>
            <p><h4>Характеристики тангенты Vector HM-44:</h4></p>            
            <ul class="marker">
                <li>Выходная мощность динамика ~0,3 Вт
                <li>Тип разъема – Icom 2,5мм/3,5мм jack
                <li>Тип разъема для подключения наушников – 3,5мм jack
                <li>Длина кабеля ~50 см
                <li>Направленный микрофон
                <li>Диапазон рабочих температур, °С: -10 / +50
            </ul>
            <p><h4>Комплект поставки:</h4></p> 
            <ul class="marker">
                <li>Тангента HM-44
                <li>Поворотная клипса
                <li>Инструкция
            </ul>
        </div>

    </div>
</div>