
<div class="container">
    <div class="text_block" >
        <h3 class="title">Автомобильные GPS/ГЛОНАСС трекеры</h3>
        <div class="text_caption">
            <p>GPS/ГЛОНАСС трекер это специальное цифровое устройство для приёма и передачи данных.</p>

            <p><em>Автомобильный <strong>gps трекер</strong> (терминал) содержит:</em></p>
            <ul class="marker">
                <li>GPS или ГЛОНАСС приёмник с помощью которого трекер определяет точные свои координаты;</li>
                <li>
                    GSM передатчик, который передаёт данные по каналу GPRS на серверный центр, 
                    оснащённым программой для спутникового мониторинга;
                </li>
                <li>Внутренняя или внешняя GPS-антенна, для более уверенной связи со спутниками;</li>
                <li>
                    Специальные разъёмы для подключения дополнительных датчиков, делающих контроль 
                    автотранспорта более эффективным. Среди них: датчики уровня и расхода топлива, 
                    датчики веса, датчики вращения и углов наклона различных механизмов;
                </li>
                <li>Внутреннюю энергонезависимую память для хранения данных при невозможности отослать их по каналу GPRS;</li>
                <li>
                    Крепкий корпус и аккумуляторная батарея на 8-10 часов делают прибор вандалоустойчивым к 
                    саботажу со стороны водителей.
                </li>
            </ul>
            <!--<img src="/img/equipment/gps-glonass-tracker.jpg" class="img_eq" alt="Схема автотрекера" title="Схема автотрекера">-->
            <p>
                Принцип работы системы спутникового мониторинга от АРТ-ТРЭК : 
                Основным устройством в этой системы является <strong>ГЛОНАСС/GPS/GSM</strong> -терминал (tracker) 
                который выполняет функции определения координат при помощи спутникового приёмника, 
                сбор информации от всех датчиков, установленных в транспортном средстве, 
                пересылку информации посредством GPRS (сотовая связь).
            </p>
            <p>
                Собранная информация дальше передаётся на сервер Wialon. 
                Затем пользователь получает всю информацию с сервера через <strong>браузер своего компьютера</strong>.
            </p>
            <img src="/img/equipment/kak-rabotaet-treker.jpg" class="img_eq" alt="Как работает трекер" title="Как работает трекер">

            <h4>Купить GPS/ГЛОНАСС трекер</h4>
            <p>
                Программное обеспечение Wialon (Виалон) на данный момент поддерживает более 350 моделей трекеров 
                (автомобильных контроллеров). Протестировав большое количество моделей различного производства 
                (Россия, Европа, Китай) мы готовы предложить Вам лучшее!
            </p>


            <div class="trackers">
                <div style="position: relative;">
                    <a href="<?php
                    echo $this->url(
                            array(
                        'controller' => 'equipment',
                        'action'     => 'tracker1'
                            ), 'default', true)
                    ?>"><img src="/img/equipment/trackers/teltonika-fm-1100.jpg" class="img_n">
                        </div>
                        <div class="tracker_text">
                            <p><a href="<?php
                                echo $this->url(
                                        array(
                                    'controller' => 'equipment',
                                    'action'     => 'tracker1'
                                        ), 'default', true)
                                ?>">GPS/ГЛОНАСС Трекер: Teltonika FM1100</a></p>
                            <p class="buttons">

                            </p>
                        </div>
                </div>


                <div class="trackers">
                    <div style="position: relative;">
                        <a href="<?php
                        echo $this->url(
                                array(
                            'controller' => 'equipment',
                            'action'     => 'tracker2'
                                ), 'default', true)
                        ?>"><img src="/img/equipment/trackers/terminal_arnavi_gl_big.png" class="img_n"></a>
                    </div>
                    <div class="tracker_text">
                        <p><a href="<?php
                            echo $this->url(
                                    array(
                                'controller' => 'equipment',
                                'action'     => 'tracker2'
                                    ), 'default', true)
                            ?>">GPS/ГЛОНАСС Трекер: Arnavi GL 2SIM</a></p>
                        <p class="buttons">

                        </p>
                    </div>
                </div>

                <div class="trackers">
                    <div style="position: relative;">
                        <a href="<?php
                        echo $this->url(
                                array(
                            'controller' => 'equipment',
                            'action'     => 'tracker3'
                                ), 'default', true)
                        ?>"><img src="/img/equipment/trackers/terminal-asc-7.jpg" class="img_n"></a>
                    </div>
                    <div class="tracker_text">
                        <p><a href="<?php
                            echo $this->url(
                                    array(
                                'controller' => 'equipment',
                                'action'     => 'tracker3'
                                    ), 'default', true)
                            ?>">GPS/ГЛОНАСС Трекер: ASC-7S</a></p>
                        <p class="buttons">

                        </p>
                    </div>
                </div>

                <div class="trackers">
                    <div style="position: relative;">
                        <a href="<?php
                        echo $this->url(
                                array(
                            'controller' => 'equipment',
                            'action'     => 'tracker4'
                                ), 'default', true)
                        ?>"><img src="/img/equipment/trackers/terminal-asc-7.jpg" class="img_n"></a>
                    </div>
                    <div class="tracker_text">
                        <p><a href="<?php
                            echo $this->url(
                                    array(
                                'controller' => 'equipment',
                                'action'     => 'tracker4'
                                    ), 'default', true)
                            ?>">GPS/ГЛОНАСС Трекер: ASC-7GW</a></p>
                        <p class="buttons">

                        </p>
                    </div>
                </div>

                <div class="trackers">
                    <div style="position: relative;">
                        <a href="<?php
                        echo $this->url(
                                array(
                            'controller' => 'equipment',
                            'action'     => 'tracker5'
                                ), 'default', true)
                        ?>"><img src="/img/equipment/trackers/terminal-asc-7.jpg" class="img_n"></a>
                    </div>
                    <div class="tracker_text">
                        <p><a href="<?php
                            echo $this->url(
                                    array(
                                'controller' => 'equipment',
                                'action'     => 'tracker5'
                                    ), 'default', true)
                            ?>">GPS/ГЛОНАСС Трекер: ASC-7G</a></p>
                        <p class="buttons">

                        </p>
                    </div>
                </div>

                <div class="trackers">
                    <div style="position: relative;">
                        <a href="<?php
                        echo $this->url(
                                array(
                            'controller' => 'equipment',
                            'action'     => 'tracker6'
                                ), 'default', true)
                        ?>"><img src="/img/equipment/trackers/v5.jpg" class="img_n"></a>
                    </div>
                    <div class="tracker_text">
                        <p><a href="<?php
                            echo $this->url(
                                    array(
                                'controller' => 'equipment',
                                'action'     => 'tracker6'
                                    ), 'default', true)
                            ?>">GALILEOSKY ГЛОНАСС/GPS v5.0</a></p>
                        <p class="buttons">

                        </p>
                    </div>
                </div>

                <div class="trackers">
                    <div style="position: relative;">
                        <a href="<?php
                        echo $this->url(
                                array(
                            'controller' => 'equipment',
                            'action'     => 'tracker7'
                                ), 'default', true)
                        ?>"><img src="/img/equipment/trackers/terminal_cguard_pro-big.png" class="img_n"></a>
                    </div>
                    <div class="tracker_text">
                        <p><a href="<?php
                            echo $this->url(
                                    array(
                                'controller' => 'equipment',
                                'action'     => 'tracker7'
                                    ), 'default', true)
                            ?>">GPS/ГЛОНАСС Трекер: cGUARD 285 GL</a></p>
                        <p class="buttons">

                        </p>
                    </div>
                </div>

                <div class="trackers">
                    <div style="position: relative;">
                        <a href="<?php
                        echo $this->url(
                                array(
                            'controller' => 'equipment',
                            'action'     => 'tracker8'
                                ), 'default', true)
                        ?>"><img src="/img/equipment/trackers/terminal_cguard_pro-big.png" class="img_n"></a>
                    </div>
                    <div class="tracker_text">
                        <p><a href="<?php
                            echo $this->url(
                                    array(
                                'controller' => 'equipment',
                                'action'     => 'tracker8'
                                    ), 'default', true)
                            ?>">GPS/ГЛОНАСС Трекер: cGUARD PRO ГЛОНАСС/GPS</a></p>
                        <p class="buttons">

                        </p>
                    </div>
                </div>

                <div class="trackers">
                    <div style="position: relative;">
                        <a href="<?php
                        echo $this->url(
                                array(
                            'controller' => 'equipment',
                            'action'     => 'tracker9'
                                ), 'default', true)
                        ?>"><img src="/img/equipment/trackers/galileo228.jpg" class="img_n"></a>
                    </div>
                    <div class="tracker_text">
                        <p><a href="<?php
                            echo $this->url(
                                    array(
                                'controller' => 'equipment',
                                'action'     => 'tracker9'
                                    ), 'default', true)
                            ?>">GPS/ГЛОНАСС Трекер: GALILEO ГЛОНАСС v2.2.8</a></p>
                        <p class="buttons">

                        </p>
                    </div>
                </div>

                <div class="trackers">
                    <div style="position: relative;">
                        <a href="<?php
                        echo $this->url(
                                array(
                            'controller' => 'equipment',
                            'action'     => 'tracker10'
                                ), 'default', true)
                        ?>"><img src="/img/equipment/trackers/terminal_cguard_pro-big.png" class="img_n"></a>
                    </div>
                    <div class="tracker_text">
                        <p><a href="<?php
                            echo $this->url(
                                    array(
                                'controller' => 'equipment',
                                'action'     => 'tracker10'
                                    ), 'default', true)
                            ?>">GPS/ГЛОНАСС Трекер: cGUARD LITE ГЛОНАСС/GPS</a></p>
                        <p class="buttons">

                        </p>
                    </div>
                </div>


                <h4>Внимание! Для оформления заказа звоните на бесплатную горячую линию: </h4>
                <h4>8(800) 500-17-14</h4>
            </div>

        </div>
    </div>