
<div class="container">
    <div class="text_block" >
        <h3 class="title">Автомобильные GPS/ГЛОНАСС трекеры</h3>
        <div class="text_caption">
            <p>GPS/ГЛОНАСС трекер это специальное цифровое устройство для приёма и передачи данных.</p>

            <p><em>Автомобильный <strong>gps трекер</strong> (терминал) содержит:</em></p>
            <ul class="marker">
                <li>GPS или ГЛОНАСС приёмник с помощью которого трекер определяет точные свои координаты;</li>
                <li>
                    GSM передатчик, который передаёт данные по каналу GPRS на серверный центр, 
                    оснащённым программой для спутникового мониторинга;
                </li>
                <li>Внутренняя или внешняя GPS-антенна, для более уверенной связи со спутниками;</li>
                <li>
                    Специальные разъёмы для подключения дополнительных датчиков, делающих контроль 
                    автотранспорта более эффективным. Среди них: датчики уровня и расхода топлива, 
                    датчики веса, датчики вращения и углов наклона различных механизмов;
                </li>
                <li>Внутреннюю энергонезависимую память для хранения данных при невозможности отослать их по каналу GPRS;</li>
                <li>
                    Крепкий корпус и аккумуляторная батарея на 8-10 часов делают прибор вандалоустойчивым к 
                    саботажу со стороны водителей.
                </li>
            </ul>
            <img src="/img/equipment/gps-glonass-tracker.jpg" class="img_eq" alt="Схема автотрекера" title="Схема автотрекера">
            <p>
                Принцип работы системы спутникового мониторинга от АРТ-ТРЭК : 
                Основным устройством в этой системы является <strong>ГЛОНАСС/GPS/GSM</strong> -терминал (tracker) 
                который выполняет функции определения координат при помощи спутникового приёмника, 
                сбор информации от всех датчиков, установленных в транспортном средстве, 
                пересылку информации посредством GPRS (сотовая связь).
            </p>
            <p>
                Собранная информация дальше передаётся на сервер Wialon. 
                Затем пользователь получает всю информацию с сервера через <strong>браузер своего компьютера</strong>.
            </p>
            <img src="/img/equipment/kak-rabotaet-treker.jpg" class="img_eq" alt="Как работает трекер" title="Как работает трекер">

            <h4>Купить GPS/ГЛОНАСС трекер</h4>
            <p>
                Программное обеспечение Wialon (Виалон) на данный момент поддерживает более 350 моделей трекеров 
                (автомобильных контроллеров). Протестировав большое количество моделей различного производства 
                (Россия, Европа, Китай) мы готовы предложить Вам лучшее!
            </p>

            <a href="#">
                <div class="trackers">
                    <div style="position: relative;">
                        <img src="/img/equipment/trackers/tracker_galileo.jpg" class="img_n">
                    </div>
                    <div class="tracker_text">
                        <p>GPS/ГЛОНАСС Трекер: Galileo</p>
                        <div class="button_b">Купить</div>
                        <div class="button_s">Цена</div>
                    </div>
                </div>
            </a>
            <a href="#">
                <div class="trackers">
                    <div style="position: relative;">
                        <img src="/img/equipment/trackers/tracker-asc-5-6.jpg" class="img_n">
                    </div>
                    <div class="tracker_text">
                        <p>GPS/ГЛОНАСС Трекер: ASC-6</p>
                        <div class="button_b">Купить</div>
                        <div class="button_s">Цена</div>
                    </div>
                </div>
            </a>
            <a href="#">
                <div class="trackers">
                    <div style="position: relative;">
                        <img src="/img/equipment/trackers/tracker-arusnavi.jpg" class="img_n">
                    </div>
                    <div class="tracker_text">
                        <p>GPS/ГЛОНАСС Трекер: Arusnavi</p>
                        <div class="button_b">Купить</div>
                        <div class="button_s">Цена</div>
                    </div>
                </div>
            </a>
            <a href="#">
                <div class="trackers">
                    <div style="position: relative;">
                        <img src="/img/equipment/trackers/tracker_galileo.jpg" class="img_n">
                    </div>
                    <div class="tracker_text">
                        <p>GPS/ГЛОНАСС Трекер: ASC-6W (Wi-Fi)</p>
                        <div class="button_b">Купить</div>
                        <div class="button_s">Цена</div>
                    </div>
                </div>
            </a>
        </div>

    </div>
</div>